export const diseases = [
     { name: 'ADHD' },
     { name: 'Acetaminophen Overdose' },
     { name: 'Acne' },
     { name: 'Actinic Keratosis' },
     { name: 'Acute Coronary Syndrome' },
     { name: 'Acute Lymphoblastic Leukemia' },
     { name: 'Acute Nonlymphocytic Leukemia' },
     { name: 'Acute Otitis Externa' },
     { name: 'Acute Promyelocytic Leukemia' },
     { name: "Addison's Disease" },
     { name: 'Adrenocortical Insufficiency' },
     { name: 'Adult Human Growth Hormone Deficiency' },
     { name: 'Agitated State' },
     { name: 'Agitation' },
     { name: 'Alcohol Dependence' },
     { name: 'Alcohol Withdrawal' },
     { name: 'Allergic Reactions' },
     { name: 'Allergic Rhinitis' },
     { name: 'Allergic Urticaria' },
     { name: 'Allergies' },
     { name: 'Alopecia' },
     { name: 'Alpha-1 Proteinase Inhibitor Deficiency' },
     { name: "Alzheimer's Disease" },
     { name: 'Amebiasis' },
     { name: 'Amenorrhea' },
     { name: 'Anal Fissure and Fistula' },
     { name: 'Anal Itching' },
     { name: 'Anaplastic Astrocytoma' },
     { name: 'Androgenetic Alopecia' },
     { name: 'Anemia' },
     { name: 'Anemia Associated with Chronic Renal Failure' },
     { name: 'Anemia, Chemotherapy Induced' },
     { name: 'Anemia, Sickle Cell' },
     { name: 'Anesthesia' },
     { name: 'Angina' },
     { name: 'Angina Pectoris Prophylaxis' },
     { name: 'Ankylosing Spondylitis' },
     { name: 'Anorexia' },
     { name: 'Anthrax' },
     { name: 'Antiphospholipid Syndrome' },
     { name: 'Anxiety' },
     { name: 'Anxiety and Stress' },
     { name: 'Aphthous Ulce' },
     { name: 'Aplastic Anemia' },
     { name: 'Arrhythmia' },
     { name: 'Asperger Syndrome' },
     { name: 'Aspergillosis, Aspergilloma' },
     { name: 'Asthma' },
     { name: 'Asthma, Maintenance' },
     { name: 'Asthma, acute' },
     { name: 'Atopic Dermatitis' },
     { name: 'Atrial Fibrillation' },
     { name: 'Atrial Flutte' },
     { name: 'Atrophic Urethritis' },
     { name: 'Atrophic Vaginitis' },
     { name: 'Auditory Processing Disorde' },
     { name: 'Autism' },
     { name: 'Autoimmune Hemolytic Anemia' },
     { name: 'Autoimmune Hepatitis' },
     { name: 'B12 Nutritional Deficiency' },
     { name: 'Back Pain' },
     { name: 'Bacteremia' },
     { name: 'Bacterial Endocarditis Prevention' },
     { name: 'Bacterial Infection' },
     { name: 'Bacterial Skin Infection' },
     { name: 'Bacterial Vaginitis' },
     { name: "Barrett's Esophagus" },
     { name: 'Basal Cell Carcinoma' },
     { name: "Behcet's Disease" },
     { name: 'Benign Essential Trem' },
     { name: 'Benign Prostatic Hyperplasia' },
     { name: 'Benzodiazepine Withdrawal' },
     { name: 'Biliary Cirrhosis' },
     { name: 'Binge Eating Disorde' },
     { name: 'Bipolar Disorde' },
     { name: 'Bladder Infection' },
     { name: 'Bleeding Disorde' },
     { name: 'Blepharitis' },
     { name: 'Body Dysmorphic Disorde' },
     { name: 'Bone infection' },
     { name: 'Borderline Personality Disorde' },
     { name: 'Bowel Preparation' },
     { name: 'Breakthrough Pain' },
     { name: 'Breast Cance' },
     { name: 'Breast Cancer, Adjuvant' },
     { name: 'Breast Cancer, Metastatic' },
     { name: 'Breast Cancer, Palliative' },
     { name: 'Breast Cancer, Prevention' },
     { name: 'Bronchitis' },
     { name: 'Bronchospasm Prophylaxis' },
     { name: 'Bulimia' },
     { name: 'Bullous Pemphigoid' },
     { name: 'Burning Mouth Syndrome' },
     { name: 'Burns, External' },
     { name: 'Bursitis' },
     { name: 'CMV Prophylaxis' },
     { name: 'COPD' },
     { name: 'COPD, Acute' },
     { name: 'COPD, Maintenance' },
     { name: 'Cachexia' },
     { name: 'Cance' },
     { name: 'Cataplexy' },
     { name: 'Cerebral Edema' },
     { name: 'Cerebral Spasticity' },
     { name: 'Cervical Dystonia' },
     { name: 'Chlamydia Infection' },
     { name: 'Chronic Fatigue Syndrome' },
     { name: 'Chronic Idiopathic Constipation' },
     { name: 'Chronic Inflammatory Demyelinating Polyradiculoneuropathy' },
     { name: 'Chronic Lymphocytic Leukemia' },
     { name: 'Chronic Myelogenous Leukemia' },
     { name: 'Chronic Myofascial Pain' },
     { name: 'Chronic Pain' },
     { name: 'Chronic Pancreatitis' },
     { name: 'Chronic Spasticity' },
     { name: 'Clostridial Infection' },
     { name: 'Cluster Headaches' },
     { name: 'Coccidioidomycosis' },
     { name: 'Cold Sores' },
     { name: 'Cold Symptoms' },
     { name: 'Colorectal Cance' },
     { name: 'Computed Tomography' },
     { name: 'Condylomata Acuminata' },
     { name: 'Conjunctivitis' },
     { name: 'Conjunctivitis, Allergic' },
     { name: 'Conjunctivitis, Bacterial' },
     { name: 'Constipation' },
     { name: 'Constipation, Acute' },
     { name: 'Constipation, Chronic' },
     { name: 'Constipation, Drug Induced' },
     { name: 'Corneal Refractive Surgery' },
     { name: 'Coronary Artery Disease' },
     { name: 'Costochondritis' },
     { name: 'Cough' },
     { name: 'Cough and Nasal Congestion' },
     { name: "Crohn's Disease" },
     { name: "Crohn's Disease, Acute" },
     { name: "Crohn's Disease, Maintenance" },
     { name: 'Cutaneous Candidiasis' },
     { name: 'Cutaneous T-cell Lymphoma' },
     { name: 'Cyclic Vomiting Syndrome' },
     { name: 'Cyclitis' },
     { name: 'Cyclothymic Disorde' },
     { name: 'Cystic Fibrosis' },
     { name: 'Dandruff' },
     { name: 'Deep Neck Infection' },
     { name: 'Deep Vein Thrombosis' },
     {
          name: 'Deep Vein Thrombosis Prophylaxis after Hip Replacement Surgery',
     },
     { name: 'Deep Vein Thrombosis, First Event' },
     { name: 'Deep Vein Thrombosis, Prophylaxis' },
     { name: 'Deep Vein Thrombosis, Recurrent Event' },
     { name: 'Dementia' },
     { name: 'Dental Abscess' },
     { name: 'Depression' },
     { name: "Dercum's Disease" },
     { name: 'Dermatitis' },
     { name: 'Dermatologic Lesion' },
     { name: 'Dermatological Disorders' },
     { name: 'Dermatomyositis' },
     { name: 'Dermatophytosis' },
     { name: 'Diabetes Insipidus' },
     { name: 'Diabetes, Type 1' },
     { name: 'Diabetes, Type 2' },
     { name: 'Diabetic Kidney Disease' },
     { name: 'Diabetic Macular Edema' },
     { name: 'Diabetic Peripheral Neuropathy' },
     { name: 'Diagnosis and Investigation' },
     { name: 'Diaper Rash' },
     { name: 'Diarrhea' },
     { name: 'Diarrhea, Acute' },
     { name: 'Diarrhea, Chronic' },
     { name: 'Dietary Fiber Supplementation' },
     { name: 'Dietary Supplementation' },
     { name: 'Dissociative Identity Disorde' },
     { name: 'Diverticulitis' },
     { name: 'Dry Eye Disease' },
     { name: 'Dry Skin' },
     { name: 'Dumping Syndrome' },
     { name: 'Duodenal Ulce' },
     { name: "Dupuytren's contracture" },
     { name: 'Dysautonomia' },
     { name: 'Dyspareunia' },
     { name: 'Dystonia' },
     { name: 'Dysuria' },
     { name: 'Ear Wax Impaction' },
     { name: 'Eczema' },
     { name: 'Edema' },
     { name: 'Ehrlichiosis' },
     { name: 'Emergency Contraception' },
     { name: 'Endometrial Cance' },
     { name: 'Endometrial Hyperplasia' },
     { name: 'Endometriosis' },
     { name: 'Enterocolitis' },
     { name: 'Eosinophilic Esophagitis' },
     { name: 'Epididymitis, Sexually Transmitted' },
     { name: 'Epilepsy' },
     { name: 'Erectile Dysfunction' },
     { name: 'Erosive Esophagitis' },
     { name: 'Esophageal Variceal Hemorrhage Prophylaxis' },
     { name: 'Expectoration' },
     { name: 'Extrapyramidal Reaction' },
     { name: 'Eye Redness' },
     { name: 'Eye Redness/Itching' },
     { name: 'Eyelash Hypotrichosis' },
     { name: 'GERD' },
     { name: 'Gallbladder Disease' },
     { name: 'Gas' },
     { name: 'Gastric Ulcer Maintenance Treatment' },
     { name: 'Gastritis/Duodenitis' },
     { name: 'Gastroenteritis' },
     { name: 'Gastrointestinal Decontamination' },
     { name: 'Gastrointestinal Hemorrhage' },
     { name: 'Gastrointestinal Stromal Tum' },
     { name: 'Gastroparesis' },
     { name: 'Gender Dysphoria' },
     { name: 'Generalized Anxiety Disorde' },
     { name: 'Giant Cell Tumor of Bone' },
     { name: 'Giardiasis' },
     { name: 'Gingivitis' },
     { name: 'Glaucoma' },
     { name: 'Glaucoma, Open Angle' },
     { name: 'Glioblastoma Multi' },
     { name: 'Glioblastoma Multiforme' },
     { name: 'Gonadotropin Inhibition' },
     { name: 'Gonococcal Infection, Uncomplicated' },
     { name: 'Gout' },
     { name: 'Gout, Acute' },
     { name: 'Gouty Arthritis' },
     { name: 'HIV Infection' },
     { name: "Hashimoto's disease" },
     { name: 'Head Injury' },
     { name: 'Head Lice' },
     { name: 'Head and Neck Cance' },
     { name: 'Headache' },
     { name: 'Heart Attack' },
     { name: 'Heart Failure' },
     { name: 'Helicobacter Pylori Infection' },
     { name: 'Hemophilia A' },
     { name: 'Hemophilia B' },
     { name: 'Hemorrhoids' },
     { name: 'Hepatic Encephalopathy' },
     { name: 'Hepatitis B' },
     { name: 'Hepatitis C' },
     { name: 'Hepatocellular Carcinoma' },
     { name: 'Herbal Supplementation' },
     { name: 'Hereditary Angioedema' },
     { name: 'Herpes Simplex' },
     { name: 'Herpes Simplex Dendritic Keratitis' },
     { name: 'Herpes Simplex, Mucocutaneous/Immunocompetent Host' },
     { name: 'Herpes Simplex, Mucocutaneous/Immunocompromised Host' },
     { name: 'Herpes Simplex, Suppression' },
     { name: 'Herpes Zoste' },
     { name: 'Herpes Zoster, Prophylaxis' },
     { name: 'Hiccups' },
     { name: 'Hidradenitis Suppurativa' },
     { name: 'High Blood Pressure' },
     { name: 'High Cholesterol' },
     { name: 'High Cholesterol, Familial Heterozygous' },
     { name: 'High Cholesterol, Familial Homozygous' },
     { name: 'Hirsutism' },
     { name: 'Histoplasmosis' },
     { name: 'Hot Flashes' },
     { name: 'Human Papilloma Virus' },
     { name: 'Human Papillomavirus Prophylaxis' },
     { name: 'Hypercalcemia of Malignancy' },
     { name: 'Hyperekplexia' },
     { name: 'Hyperhidrosis' },
     { name: 'Hyperkalemia' },
     { name: 'Hyperlipoproteinemia' },
     { name: 'Hyperlipoproteinemia Type IIa, Elevated LDL' },
     { name: 'Hyperphosphatemia' },
     { name: 'Hyperphosphatemia of Renal Failure' },
     { name: 'Hyperprolactinemia' },
     { name: 'Hypersomnia' },
     { name: 'Hypertensive Emergency' },
     { name: 'Hyperthyroidism' },
     { name: 'Hypertriglyceridemia' },
     { name: 'Hypoactive Sexual Desire Disorde' },
     { name: 'Hypocalcemia' },
     { name: 'Hypodermoclysis' },
     { name: 'Hypoestrogenism' },
     { name: 'Hypogonadism, Male' },
     { name: 'Hypokalemic Periodic Paralysis' },
     { name: 'Hypomagnesemia' },
     { name: 'Hypoparathyroidism' },
     { name: 'Hypotension' },
     { name: 'Hypothyroidism, After Thyroid Removal' },
     { name: 'ICU Agitation' },
     { name: 'Ichthyosis' },
     { name: 'Idiopathic Thrombocytopenic Purpura' },
     { name: 'Immunosuppression' },
     { name: 'Impetig' },
     { name: 'Indigestion' },
     { name: 'Infection Prophylaxis' },
     { name: 'Inflammatory Bowel Disease' },
     { name: 'Inflammatory Conditions' },
     { name: 'Influenza' },
     { name: 'Influenza Prophylaxis' },
     { name: 'Insomnia' },
     { name: 'Insomnia, Stimulant-Associated' },
     { name: 'Insulin Resistance Syndrome' },
     { name: 'Intermittent Claudication' },
     { name: 'Interstitial Cystitis' },
     { name: 'Intraabdominal Infection' },
     { name: 'Intraocular Hypertension' },
     { name: 'Iritis' },
     { name: 'Iron Deficiency Anemia' },
     { name: 'Irritable Bowel Syndrome' },
     { name: 'Ischemic Stroke' },
     { name: 'Ischemic Stroke, Prophylaxis' },
     { name: 'Jet Lag' },
     { name: 'Joint Infection' },
     { name: 'Juvenile Idiopathic Arthritis' },
     { name: 'Juvenile Rheumatoid Arthritis' },
     { name: 'Keratitis' },
     { name: 'Keratoconjunctivitis Sicca' },
     { name: 'Keratosis' },
     { name: 'Kidney Infections' },
     { name: 'Labor Induction' },
     { name: 'Labor Pain' },
     { name: 'Lactation Augmentation' },
     { name: 'Lactose Intolerance' },
     { name: 'Left Ventricular Dysfunction' },
     { name: 'Lennox-Gastaut Syndrome' },
     { name: 'Leukemia' },
     { name: 'Lichen Planus' },
     { name: 'Lichen Sclerosus' },
     { name: 'Light Anesthesia' },
     { name: 'Light Sedation' },
     { name: 'Lipodystrophy' },
     { name: 'Liver Magnetic Resonance Imaging' },
     { name: 'Local Anesthesia' },
     { name: 'Lyme Disease' },
     { name: 'Lyme Disease, Erythema Chronicum Migrans' },
     { name: 'Lyme Disease, Neurologic' },
     { name: 'Lymphocytic Colitis' },
     { name: 'Lymphoma' },
     { name: 'Macular Degeneration' },
     { name: 'Macular Edema' },
     { name: 'Major Depressive Disorde' },
     { name: 'Malaria' },
     { name: 'Malaria Prevention' },
     { name: 'Mania' },
     { name: 'Mantle Cell Lymphoma' },
     { name: 'Melanoma' },
     { name: 'Melanoma, Metastatic' },
     { name: 'Melasma' },
     { name: "Meniere's Disease" },
     { name: 'Meningococcal Meningitis Prophylaxis' },
     { name: 'Menopausal Disorders' },
     { name: 'Menorrhagia' },
     { name: 'Menstrual Disorders' },
     { name: 'Methicillin-Resistant Staphylococcus Aureus Infection' },
     { name: 'Migraine' },
     { name: 'Migraine Prevention' },
     { name: 'Mild Cognitive Impairment' },
     { name: 'Mitral Valve Prolapse' },
     { name: 'Mixed Connective Tissue Disease' },
     { name: 'Mononucleosis' },
     { name: 'Motion Sickness' },
     { name: 'Mountain Sickness / Altitude Sickness' },
     { name: 'Mucositis' },
     { name: 'Multiple Myeloma' },
     { name: 'Multiple Sclerosis' },
     { name: 'Muscle Pain' },
     { name: 'Muscle Spasm' },
     { name: 'Myasthenia Gravis' },
     { name: 'Mycobacterium avium-intracellulare, Treatment' },
     { name: 'Mycoplasma Pneumonia' },
     { name: 'Myelodysplastic Syndrome' },
     { name: 'Myelofibrosis' },
     { name: 'Myeloproliferative Disorders' },
     { name: 'Myotonia Congenita' },
     { name: 'NSAID-Induced Gastric Ulce' },
     { name: 'Narcolepsy' },
     { name: 'Nasal Carriage of Staphylococcus aureus' },
     { name: 'Nasal Congestion' },
     { name: 'Nasal Polyps' },
     { name: 'Nausea/Vomiting' },
     { name: 'Nausea/Vomiting of Pregnancy' },
     { name: 'Nausea/Vomiting, Chemotherapy Induced' },
     { name: 'Nausea/Vomiting, Postoperative' },
     { name: 'Neck Pain' },
     { name: 'Nephrotic Syndrome' },
     { name: 'Neuralgia' },
     { name: 'Neuropathic Pain' },
     { name: 'Neutropenia' },
     { name: 'Neutropenia Associated with Chemotherapy' },
     { name: 'New Daily Persistent Headache' },
     { name: 'Night Terrors' },
     { name: 'Nightmares' },
     { name: 'Nocturnal Leg Cramps' },
     { name: "Non-Hodgkin's Lymphoma" },
     { name: 'Non-Small Cell Lung Cance' },
     { name: 'Noninfectious Colitis' },
     { name: 'Nonoccupational Exposure' },
     { name: 'Not Listed / Othe' },
     { name: 'Obesity' },
     { name: 'Obsessive Compulsive Disorde' },
     { name: 'Obstructive Sleep Apnea/Hypopnea Syndrome' },
     { name: 'Occipital Neuralgia' },
     { name: 'Occupational Exposure' },
     { name: 'Oligospermia' },
     { name: 'Onychomycosis, Fingernail' },
     { name: 'Onychomycosis, Toenail' },
     { name: 'Oophorectomy' },
     { name: 'Ophthalmic Surgery' },
     { name: 'Opiate Adjunct' },
     { name: 'Opiate Dependence' },
     { name: 'Opiate Withdrawal' },
     { name: 'Opioid Overdose' },
     { name: 'Opioid-Induced Constipation' },
     { name: 'Oppositional Defiant Disorde' },
     { name: 'Oral Thrush' },
     { name: 'Oral and Dental Conditions' },
     { name: 'Organ Transplant, Rejection Prophylaxis' },
     { name: 'Organ Transplant, Rejection Reversal' },
     { name: 'Osteoarthritis' },
     { name: 'Osteolytic Bone Lesions of Multiple Myeloma' },
     { name: 'Osteolytic Bone Metastases of Solid Tumors' },
     { name: 'Osteoporosis' },
     { name: 'Otitis Externa' },
     { name: 'Otitis Media' },
     { name: 'Ovarian Cance' },
     { name: 'Ovarian Cysts' },
     { name: 'Overactive Bladde' },
     { name: 'Ovulation Induction' },
     { name: "Paget's Disease" },
     { name: 'Pain' },
     { name: 'Pain/Feve' },
     { name: 'Pancreatic Cance' },
     { name: 'Pancreatic Exocrine Dysfunction' },
     { name: 'Panic Disorde' },
     { name: 'Paranoid Disorde' },
     { name: "Parkinson's Disease" },
     { name: 'Parkinsonism' },
     { name: 'Pe' },
     { name: 'Pediatric Growth Hormone Deficiency' },
     { name: 'Pelvic Inflammatory Disease' },
     { name: 'Pemphigoid' },
     { name: 'Pemphigus' },
     { name: 'Peptic Ulce' },
     { name: 'Percutaneous Coronary Intervention' },
     { name: 'Performance Anxiety' },
     { name: 'Perimenopausal Symptoms' },
     { name: 'Period Pain' },
     { name: 'Periodic Limb Movement Disorde' },
     { name: 'Periodontitis' },
     { name: 'Perioral Dermatitis' },
     { name: 'Peripheral Arterial Disease' },
     { name: 'Peripheral Neuropathy' },
     { name: 'Peritonitis' },
     { name: 'Persistent Depressive Disorde' },
     { name: 'Pertussis' },
     { name: 'Pertussis Prophylaxis' },
     { name: 'Pharyngitis' },
     { name: 'Photoaging of the Skin' },
     { name: 'Pityriasis rubra pilaris' },
     { name: 'Plaque Psoriasis' },
     { name: 'Platelet Aggregation Inhibition' },
     { name: 'Pneumococcal Disease Prophylaxis' },
     { name: 'Pneumonia' },
     { name: 'Polycystic Ovary Syndrome' },
     { name: 'Polycythemia Vera' },
     { name: 'Polymyositis/Dermatomyositis' },
     { name: 'Post Traumatic Stress Disorde' },
     { name: 'Post-Cholecystectomy Diarrhea' },
     { name: 'Postherpetic Neuralgia' },
     { name: 'Postmenopausal Symptoms' },
     { name: 'Postoperative Increased Intraocular Pressure' },
     { name: 'Postoperative Ocular Inflammation' },
     { name: 'Postoperative Pain' },
     { name: 'Postpartum Depression' },
     { name: 'Postural Orthostatic Tachycardia Syndrome' },
     { name: 'Pre-Exposure Prophylaxis' },
     { name: 'Precocious Puberty' },
     { name: 'Premature Ejaculation' },
     { name: 'Premature Lab' },
     { name: 'Premature Ventricular Depolarizations' },
     { name: 'Premenstrual Dysphoric Disorde' },
     { name: 'Premenstrual Syndrome' },
     { name: 'Prevention of Bladder infection' },
     { name: 'Prevention of Cardiovascular Disease' },
     { name: 'Prevention of Dental Caries' },
     { name: 'Prevention of Hypokalemia' },
     { name: 'Prevention of Osteoporosis' },
     { name: 'Prevention of Thromboembolism in Atrial Fibrillation' },
     { name: 'Primary Hyperaldosteronism' },
     { name: 'Primary Immunodeficiency Syndrome' },
     { name: 'Primary Nocturnal Enuresis' },
     { name: 'Primary Ovarian Failure' },
     { name: 'Progesterone Insufficiency' },
     { name: 'Prostate Cance' },
     { name: 'Prostatitis' },
     { name: 'Pruritus' },
     { name: 'Pseudobulbar Affect' },
     { name: 'Pseudotumor Cerebri' },
     { name: 'Psoriasis' },
     { name: 'Psoriatic Arthritis' },
     { name: 'Psychosis' },
     { name: 'Pudendal Neuralgia' },
     { name: 'Pulmonary Edema' },
     { name: 'Pulmonary Embolism' },
     { name: 'Pulmonary Embolism, First Event' },
     { name: 'Pulmonary Hypertension' },
     { name: 'Pupillary Dilation' },
     { name: 'Radionuclide Myocardial Perfusion Study' },
     { name: 'Rat-bite Feve' },
     { name: "Raynaud's Syndrome" },
     { name: 'Reflex Sympathetic Dystrophy Syndrome' },
     { name: 'Renal Cell Carcinoma' },
     { name: 'Renal Tubular Acidosis' },
     { name: 'Restless Legs Syndrome' },
     { name: 'Reversal of Nondepolarizing Muscle Relaxants' },
     { name: 'Reversal of Opioid Sedation' },
     { name: 'Rheumatoid Arthritis' },
     { name: 'Rhinitis' },
     { name: 'Rhinorrhea' },
     { name: 'Rosacea' },
     { name: 'Salmonella Gastroenteritis' },
     { name: 'Sarcoidosis' },
     { name: 'Scabies' },
     { name: 'Schilling Test' },
     { name: 'Schizoaffective Disorde' },
     { name: 'Schizophrenia' },
     { name: 'Schnitzler Syndrome' },
     { name: 'Sciatica' },
     { name: 'Seasonal Affective Disorde' },
     { name: 'Seasonal Allergic Conjunctivitis' },
     { name: 'Seborrheic Dermatitis' },
     { name: 'Secondary Hyperparathyroidism' },
     { name: 'Sedation' },
     { name: 'Seizure Prevention' },
     { name: 'Seizures' },
     { name: 'Sexual Dysfunction, SSRI Induced' },
     { name: 'Shift Work Sleep Disorde' },
     { name: 'Sinus Symptoms' },
     { name: 'Sinusitis' },
     { name: "Sjogren's Syndrome" },
     { name: 'Skin Cance' },
     { name: 'Skin Disinfection, Preoperative' },
     { name: 'Skin Rash' },
     { name: 'Skin and Structure Infection' },
     { name: 'Skin or Soft Tissue Infection' },
     { name: 'Small Bowel or Pancreatic Fistula' },
     { name: 'Smoking Cessation' },
     { name: 'Social Anxiety Disorde' },
     { name: 'Soft Tissue Sarcoma' },
     { name: 'Somat' },
     { name: 'Sore Throat' },
     { name: 'Spondyloarthritis' },
     { name: 'Spondylolisthesis' },
     { name: 'Squamous Cell Carcinoma' },
     { name: 'Status Epilepticus' },
     { name: 'Steroid Responsive Inflammatory Conditions' },
     { name: "Still's Disease" },
     { name: 'Stomach Cance' },
     { name: 'Stomach Ulce' },
     { name: 'Strabismus' },
     { name: 'Strep Throat' },
     { name: 'Streptococcal Infection' },
     { name: 'Stress Ulcer Prophylaxis' },
     { name: 'Strongyloidiasis' },
     { name: 'Subarachnoid Hemorrhage' },
     { name: 'Submental Fullness' },
     { name: 'Sunburn' },
     { name: 'Supraventricular Tachycardia' },
     { name: 'Surgical Prophylaxis' },
     { name: 'Swine Flu' },
     { name: 'Syringomyelia' },
     { name: 'Systemic Lupus Erythematosus' },
     { name: 'Systemic Mastocytosis' },
     { name: 'Systemic Sclerosis' },
     { name: 'TSH Suppression' },
     { name: 'Temporomandibular Joint Disorde' },
     { name: 'Tendonitis' },
     { name: 'Thrombocythemia' },
     { name: 'Thromboembolic Stroke Prophylaxis' },
     { name: 'Thyroid Cance' },
     { name: 'Thyrotoxicosis' },
     { name: 'Tinea Corporis' },
     { name: 'Tinea Cruris' },
     { name: 'Tinea Pedis' },
     { name: 'Tinea Versicol' },
     { name: 'Tinnitus' },
     { name: 'Tonsillitis/Pharyngitis' },
     { name: 'Topical Disinfection' },
     { name: "Tourette's Syndrome" },
     { name: 'Transient Ischemic Attack' },
     { name: "Traveler's Diarrhea" },
     { name: 'Trichomoniasis' },
     { name: 'Trichotillomania' },
     { name: 'Trigeminal Neuralgia' },
     { name: 'Tuberculosis, Latent' },
     { name: 'Tympanostomy Tube Placement Surgery' },
     { name: 'Ulcerative Colitis' },
     { name: 'Ulcerative Colitis, Active' },
     { name: 'Ulcerative Colitis, Maintenance' },
     { name: 'Ulcerative Proctitis' },
     { name: 'Underactive Thyroid' },
     { name: 'Undifferentiated Connective Tissue Disease' },
     { name: 'Upper Limb Spasticity' },
     { name: 'Upper Respiratory Tract Infection' },
     { name: 'Urinary Incontinence' },
     { name: 'Urinary Retention' },
     { name: 'Urinary Tract Infection' },
     { name: 'Urinary Tract Stones' },
     { name: 'Urticaria' },
     { name: 'Uterine Bleeding' },
     { name: 'Uterine Fibroids' },
     { name: 'Uveitis' },
     { name: 'Uveitis, Posteri' },
     { name: 'Vaginal Yeast Infection' },
     { name: 'Varicella-Zoste' },
     { name: 'Ventricular Arrhythmia' },
     { name: 'Ventricular Fibrillation' },
     { name: 'Ventricular Tachycardia' },
     { name: 'Vertig' },
     { name: 'Vitamin B12 Deficiency' },
     { name: 'Vitamin D Deficiency' },
     { name: 'Vitamin/Mineral Supplementation and Deficiency' },
     {
          name: 'Vitamin/Mineral Supplementation during Pregnancy/Lactation',
     },
     { name: 'Vulvodynia' },
     { name: 'Warts' },
     { name: "Wegener's Granulomatosis" },
     { name: 'Weight Loss' },
     { name: 'Wolff-Parkinson-White Syndrome' },
     { name: 'Xerostomia' },
     { name: 'Yellow Fever Prophylaxis' },
     { name: 'Zollinger-Ellison Syndrome' },
];
