export const medicines = [
     { name: 'A  B Otic' },
     { name: 'Abacavir  dolutegravir  lamivudine' },
     { name: 'Abacavir  lamivudine' },
     { name: 'Abatacept' },
     { name: 'Abilify' },
     { name: 'Abilify Discmelt' },
     { name: 'Abilify Maintena' },
     { name: 'Abiraterone' },
     { name: 'AbobotulinumtoxinA' },
     { name: 'Abreva' },
     { name: 'Absorica' },
     { name: 'Abstral' },
     { name: 'Acamprosate' },
     { name: 'Acanya' },
     { name: 'Acarbose' },
     { name: 'Accolate' },
     { name: 'Accutane' },
     { name: 'Acetaminophen' },
     { name: 'Acetaminophen  aspirin' },
     { name: 'Acetaminophen  aspirin  caffeine' },
     { name: 'Acetaminophen  aspirin  caffeine  salicylamide' },
     { name: 'Acetaminophen  butalbital' },
     { name: 'Acetaminophen  butalbital  caffeine' },
     { name: 'Acetaminophen  butalbital  caffeine  codeine' },
     { name: 'Acetaminophen  caffeine' },
     { name: 'Acetaminophen  caffeine  dihydrocodeine' },
     { name: 'Acetaminophen  caffeine  isometheptene mucate' },
     { name: 'Acetaminophen  caffeine  magnesium salicylate' },
     { name: 'Acetaminophen  chlorpheniramine' },
     {
          name: 'Acetaminophen  chlorpheniramine  dextromethorphan  pseudoephedrine',
     },
     { name: 'Acetaminophen  chlorpheniramine  phenylephrine' },
     { name: 'Acetaminophen  codeine' },
     { name: 'Acetaminophen  dexbrompheniramine  pseudoephedrine' },
     {
          name: 'Acetaminophen  dextromethorphan  guaifenesin  phenylephrine',
     },
     {
          name: 'Acetaminophen  dextromethorphan  guaifenesin  pseudoephedrine',
     },
     { name: 'Acetaminophen  dextromethorphan  pseudoephedrine' },
     { name: 'Acetaminophen  dichloralphenazone  isometheptene mucate' },
     { name: 'Acetaminophen  diphenhydramine' },
     { name: 'Acetaminophen  hydrocodone' },
     { name: 'Acetaminophen  oxycodone' },
     { name: 'Acetaminophen  pamabrom' },
     { name: 'Acetaminophen  phenylephrine' },
     { name: 'Acetaminophen  phenyltoloxamine' },
     { name: 'Acetaminophen  propoxyphene' },
     { name: 'Acetaminophen  tramadol' },
     { name: 'Acetazolamide' },
     { name: 'Acetic acid  hydrocortisone' },
     { name: 'Acetylcysteine' },
     { name: 'Acidophilus' },
     { name: 'Aciphex' },
     { name: 'Acitretin' },
     { name: 'Aclidinium' },
     { name: 'Acnex' },
     { name: 'Acrivastine  pseudoephedrine' },
     { name: 'Actemra' },
     { name: 'Actifed' },
     { name: 'Actiq' },
     { name: 'Activella' },
     { name: 'ActoPlus Met' },
     { name: 'Actonel' },
     { name: 'Actos' },
     { name: 'Acular LS' },
     { name: 'Acuvail' },
     { name: 'Acyclovir' },
     { name: 'Aczone' },
     { name: 'Adalat CC' },
     { name: 'Adalimumab' },
     { name: 'Adapalene' },
     { name: 'Adapalene  benzoyl peroxide' },
     { name: 'Adcirca' },
     { name: 'Adderall' },
     { name: 'Adderall XR' },
     { name: 'Addyi' },
     { name: 'Adenosine' },
     { name: 'AdipexP' },
     { name: 'Adipost' },
     { name: 'Adoxa' },
     { name: 'Advair Diskus' },
     { name: 'Advair HFA' },
     { name: 'Advicor' },
     { name: 'Advil' },
     { name: 'Advil Cold and Sinus' },
     { name: 'Advil Cold and Sinus LiquiGels' },
     { name: 'Advil LiquiGels' },
     { name: 'Adzenys XRODT' },
     { name: 'Aerobid' },
     { name: 'Afinitor' },
     { name: 'Aflibercept' },
     { name: 'Afrezza' },
     { name: 'Afrin' },
     { name: 'Afrin 4 Hour Extra Moisturizing' },
     { name: 'Aftera' },
     { name: 'Aggrenox' },
     { name: 'Alahist LQ' },
     { name: 'Alavert D12 Hour Allergy and Sinus' },
     { name: 'Albendazole' },
     { name: 'Albenza' },
     { name: 'Albiglutide' },
     { name: 'Albuterol' },
     { name: 'Albuterol  ipratropium' },
     { name: 'Alcaftadine' },
     { name: 'Alclometasone' },
     { name: 'Aldactazide' },
     { name: 'Aldactone' },
     { name: 'Aldara' },
     { name: 'Aldesleukin' },
     { name: 'Alendronate' },
     { name: 'Alesse' },
     { name: 'Aleve' },
     { name: 'Alfuzosin' },
     { name: 'Alirocumab' },
     { name: 'Aliskiren' },
     { name: 'Aliskiren  hydrochlorothiazide' },
     { name: 'AlkaSeltzer Plus Cold' },
     { name: 'Allegra' },
     { name: 'Allegra Allergy' },
     { name: 'AllegraD 12 Hour' },
     { name: 'AllegraD 24 Hour' },
     { name: 'Allergy DN PE' },
     { name: 'Allerx Dose Pack DF' },
     { name: 'Alli' },
     { name: 'Allopurinol' },
     { name: 'Almotriptan' },
     { name: 'Alosetron' },
     { name: 'Alpha 1proteinase inhibitor' },
     { name: 'Alphagan P' },
     { name: 'Alprazolam' },
     { name: 'Alprazolam Intensol' },
     { name: 'Alprostadil' },
     { name: 'Alrex' },
     { name: 'Altabax' },
     { name: 'Altace' },
     { name: 'Altavera' },
     { name: 'Aluminum chloride hexahydrate' },
     { name: 'Aluminum hydroxide  magnesium hydroxide  simethicone' },
     { name: 'Alvesco' },
     { name: 'AmLactin' },
     { name: 'Amantadine' },
     { name: 'Amaryl' },
     { name: 'Ambien' },
     { name: 'Ambien CR' },
     { name: 'Ambrisentan' },
     { name: 'Amcinonide' },
     { name: 'Amerge' },
     { name: 'Amethia' },
     { name: 'Amethia Lo' },
     { name: 'Amethyst' },
     { name: 'Amikacin' },
     { name: 'Amiodarone' },
     { name: 'Amitiza' },
     { name: 'Amitriptyline' },
     { name: 'Amitriptyline  chlordiazepoxide' },
     { name: 'Amitriptyline  perphenazine' },
     { name: 'Amlodipine' },
     { name: 'Amlodipine  atorvastatin' },
     { name: 'Amlodipine  benazepril' },
     { name: 'Amlodipine  hydrochlorothiazide  olmesartan' },
     { name: 'Amlodipine  olmesartan' },
     { name: 'Amlodipine  telmisartan' },
     { name: 'Amlodipine  valsartan' },
     { name: 'Ammonium lactate' },
     { name: 'Ammonium lactate  halobetasol' },
     { name: 'Amnesteem' },
     { name: 'Amoxapine' },
     { name: 'Amoxicillin' },
     { name: 'Amoxicillin  clarithromycin  lansoprazole' },
     { name: 'Amoxicillin  clavulanate' },
     { name: 'Amoxil' },
     { name: 'Amphetamine' },
     { name: 'Amphetamine  dextroamphetamine' },
     { name: 'Ampyra' },
     { name: 'Amrix' },
     { name: 'Anacin' },
     { name: 'Anafranil' },
     { name: 'Anakinra' },
     { name: 'AnalpramHC' },
     { name: 'Anaprox' },
     { name: 'Anastrozole' },
     { name: 'AndroGel' },
     { name: 'Androderm' },
     { name: 'Angeliq' },
     { name: 'Angiomax' },
     { name: 'Anoro Ellipta' },
     { name: 'Ansaid' },
     { name: 'Antabuse' },
     { name: 'Antara' },
     { name: 'AntiDiarrheal' },
     { name: 'Antihemophilic factor' },
     { name: 'Antipyrine  benzocaine' },
     { name: 'AnucortHC' },
     { name: 'Apidra' },
     { name: 'Apixaban' },
     { name: 'Aplenzin' },
     { name: 'Apokyn' },
     { name: 'Apomorphine' },
     { name: 'Apremilast' },
     { name: 'Aprepitant' },
     { name: 'Apri' },
     { name: 'Apriso' },
     { name: 'Aptensio XR' },
     { name: 'Aptiom' },
     { name: 'Aranesp' },
     { name: 'Arava' },
     { name: 'Arcalyst' },
     { name: 'Arformoterol' },
     { name: 'Aricept' },
     { name: 'Arimidex' },
     { name: 'Aripiprazole' },
     { name: 'Aristocort' },
     { name: 'Aristocort A' },
     { name: 'Aristospan' },
     { name: 'Arixtra' },
     { name: 'Armodafinil' },
     { name: 'Armour Thyroid' },
     { name: 'Arnuity Ellipta' },
     { name: 'Aromasin' },
     { name: 'Artane' },
     { name: 'Arthrotec' },
     { name: 'Asacol' },
     { name: 'Asacol HD' },
     { name: 'Ascorbic acid' },
     { name: 'Asenapine' },
     { name: 'Ashlyna' },
     { name: 'Asmanex Twisthaler' },
     { name: 'Aspirin' },
     { name: 'Aspirin  butalbital  caffeine' },
     { name: 'Aspirin  butalbital  caffeine  codeine' },
     { name: 'Aspirin  caffeine' },
     { name: 'Aspirin  caffeine  orphenadrine' },
     { name: 'Aspirin  carisoprodol' },
     { name: 'Aspirin  carisoprodol  codeine' },
     { name: 'Aspirin  dipyridamole' },
     { name: 'Aspirin  meprobamate' },
     { name: 'Aspirin  oxycodone' },
     { name: 'Astelin' },
     { name: 'Astepro' },
     { name: 'Asthmanefrin' },
     { name: 'Atacand' },
     { name: 'Atarax' },
     { name: 'Atelvia' },
     { name: 'Atenolol' },
     { name: 'Atenolol  chlorthalidone' },
     { name: 'Ativan' },
     { name: 'Atomoxetine' },
     { name: 'Atorvastatin' },
     { name: 'Atovaquone' },
     { name: 'Atovaquone  proguanil' },
     { name: 'Atralin' },
     { name: 'Atripla' },
     { name: 'Atropine  difenoxin' },
     { name: 'Atropine  diphenoxylate' },
     { name: 'Atropine  hyoscyamine  phenobarbital  scopolamine' },
     { name: 'Atrovent' },
     { name: 'Atrovent Nasal' },
     { name: 'Aubagio' },
     { name: 'Aubra' },
     { name: 'Augmentin' },
     { name: 'Augmentin XR' },
     { name: 'Avalide' },
     { name: 'Avanafil' },
     { name: 'Avandia' },
     { name: 'Avapro' },
     { name: 'Avastin' },
     { name: 'Aveed' },
     { name: 'Avelox' },
     { name: 'Aviane' },
     { name: 'Avinza' },
     { name: 'Avodart' },
     { name: 'Avonex' },
     { name: 'Avonex Pen' },
     { name: 'Axert' },
     { name: 'Axid' },
     { name: 'Axid AR' },
     { name: 'Axiron' },
     { name: 'Ayr Saline Nasal' },
     { name: 'Azacitidine' },
     { name: 'Azathioprine' },
     { name: 'Azelaic acid' },
     { name: 'Azelastine' },
     { name: 'Azelastine  fluticasone' },
     { name: 'Azelex' },
     { name: 'Azilect' },
     { name: 'Azilsartan medoxomil' },
     { name: 'Azilsartan medoxomil  chlorthalidone' },
     { name: 'Azithromycin' },
     { name: 'Azithromycin Dose Pack' },
     { name: 'AzoStandard' },
     { name: 'Azopt' },
     { name: 'Azor' },
     { name: 'Azurette' },
     { name: 'B  O Supprettes' },
     { name: 'Bacitracin  neomycin  polymyxin b' },
     { name: 'Bacitracin  polymyxin b' },
     { name: 'Baclofen' },
     { name: 'Bactrim' },
     { name: 'Bactrim DS' },
     { name: 'Bactroban' },
     { name: 'Balacet' },
     { name: 'Balsalazide' },
     { name: 'Balsam peru  castor oil  trypsin' },
     { name: 'Balziva' },
     { name: 'Banzel' },
     { name: 'Barium sulfate' },
     { name: 'Basaglar' },
     { name: 'Bayer Aspirin' },
     { name: 'Bazedoxifene  conjugated estrogens' },
     { name: 'Beclomethasone' },
     { name: 'Belbuca' },
     { name: 'Belimumab' },
     { name: 'Belladonna  opium' },
     { name: 'Belsomra' },
     { name: 'Belviq' },
     { name: 'Benadryl' },
     { name: 'Benadryl Allergy' },
     { name: 'Benazepril' },
     { name: 'Benazepril  hydrochlorothiazide' },
     { name: 'Benicar' },
     { name: 'Benicar HCT' },
     { name: 'Benlysta' },
     { name: 'Bensal HP' },
     { name: 'Bentyl' },
     { name: 'BenzEFoam' },
     { name: 'BenzEFoam Ultra' },
     { name: 'Benzaclin' },
     { name: 'Benzocaine' },
     { name: 'Benzoic acid  salicylic acid' },
     { name: 'Benzonatate' },
     { name: 'Benzoyl peroxide' },
     { name: 'Benzoyl peroxide  clindamycin' },
     { name: 'Benzoyl peroxide  erythromycin' },
     { name: 'Benzoyl peroxide  sulfur' },
     { name: 'Benzphetamine' },
     { name: 'Benztropine' },
     { name: 'Bepotastine' },
     { name: 'Bepreve' },
     { name: 'Berinert' },
     { name: 'Betamethasone' },
     { name: 'Betamethasone  calcipotriene' },
     { name: 'Betapace' },
     { name: 'Betaseron' },
     { name: 'Bethanechol' },
     { name: 'Bevacizumab' },
     { name: 'Bextra' },
     { name: 'Beyaz' },
     { name: 'Biafine' },
     { name: 'Biaxin' },
     { name: 'Biaxin XL' },
     { name: 'Bicalutamide' },
     { name: 'Bicillin LA' },
     { name: 'Bimatoprost' },
     { name: 'Bioflavonoids  zinc glycinate' },
     { name: 'Biotin' },
     { name: 'Bisacodyl' },
     {
          name: 'Bisacodyl  polyethylene glycol 3350  potassium chloride  sodium bicarbonate  sodium chloride',
     },
     { name: 'Bismuth subcitrate potassium  metronidazole  tetracycline' },
     { name: 'Bismuth subgallate' },
     { name: 'Bismuth subsalicylate' },
     { name: 'Bisoprolol' },
     { name: 'Bisoprolol  hydrochlorothiazide' },
     { name: 'Blisovi 24 Fe' },
     { name: 'Blisovi Fe 1  20' },
     { name: 'Blistex' },
     { name: 'Bonine' },
     { name: 'Boniva' },
     { name: 'Bontril Slow Release' },
     { name: 'Bosutinib' },
     { name: 'Botox' },
     { name: 'Botox Cosmetic' },
     { name: 'Breo Ellipta' },
     { name: 'Brexpiprazole' },
     { name: 'Brilinta' },
     { name: 'Brimonidine' },
     { name: 'Brimonidine  timolol' },
     { name: 'Brisdelle' },
     { name: 'Brivaracetam' },
     { name: 'Briviact' },
     { name: 'Brodalumab' },
     { name: 'Bromfed DM' },
     { name: 'Bromocriptine' },
     { name: 'Brompheniramine' },
     { name: 'Brompheniramine  dextromethorphan  pseudoephedrine' },
     { name: 'Bronkaid' },
     { name: 'Brovana' },
     { name: 'BuSpar' },
     { name: 'Budeprion SR' },
     { name: 'Budeprion XL' },
     { name: 'Budesonide' },
     { name: 'Budesonide  formoterol' },
     { name: 'Bumetanide' },
     { name: 'Bunavail' },
     { name: 'Bupivacaine' },
     { name: 'Bupivacaine liposome' },
     { name: 'Buprenex' },
     { name: 'Buprenorphine' },
     { name: 'Buprenorphine  naloxone' },
     { name: 'Buproban' },
     { name: 'Bupropion' },
     { name: 'Bupropion  naltrexone' },
     { name: 'Buspirone' },
     { name: 'Butabarbital' },
     { name: 'Butorphanol' },
     { name: 'Butrans' },
     { name: 'Bydureon' },
     { name: 'Byetta' },
     { name: 'Bystolic' },
     { name: 'Cabergoline' },
     { name: 'Cafergot' },
     { name: 'Caffeine' },
     { name: 'Caffeine  ergotamine' },
     { name: 'Calamine' },
     { name: 'Calan SR' },
     { name: 'CalciChew' },
     { name: 'Calcipotriene' },
     { name: 'Calcitonin' },
     { name: 'Calcitriol' },
     { name: 'Calcium acetate' },
     { name: 'Calcium carbonate' },
     { name: 'Calmoseptine' },
     { name: 'Caltrate 600D' },
     { name: 'Cambia' },
     { name: 'Camila' },
     { name: 'Camphor  menthol' },
     { name: 'Campral' },
     { name: 'Camrese' },
     { name: 'CamreseLo' },
     { name: 'Canagliflozin' },
     { name: 'Canasa' },
     { name: 'Candesartan' },
     { name: 'Capecitabine' },
     { name: 'Capsaicin' },
     { name: 'Capsaicin  menthol  methyl salicylate' },
     { name: 'Capzasin' },
     { name: 'CapzasinP' },
     { name: 'Carac' },
     { name: 'Carafate' },
     { name: 'Carbamazepine' },
     { name: 'Carbamide peroxide' },
     { name: 'Carbatrol' },
     { name: 'Carbidopa  entacapone  levodopa' },
     { name: 'Carbidopa  levodopa' },
     { name: 'Carbinoxamine' },
     { name: 'Carboplatin' },
     { name: 'Cardizem' },
     { name: 'Cardizem CD' },
     { name: 'Cardura' },
     { name: 'Cardura XL' },
     { name: 'Cariprazine' },
     { name: 'Carisoprodol' },
     { name: 'Carmol 20' },
     { name: 'Cartia XT' },
     { name: 'Carvedilol' },
     { name: 'Casodex' },
     { name: 'Cataflam' },
     { name: 'Catapres' },
     { name: 'Caverject' },
     { name: 'Caziant' },
     { name: 'Cedax' },
     { name: 'Cefdinir' },
     { name: 'Cefditoren' },
     { name: 'Cefepime' },
     { name: 'Cefixime' },
     { name: 'Cefpodoxime' },
     { name: 'Cefprozil' },
     { name: 'Ceftibuten' },
     { name: 'Ceftin' },
     { name: 'Ceftriaxone' },
     { name: 'Cefuroxime' },
     { name: 'Cefzil' },
     { name: 'Celebrex' },
     { name: 'Celecoxib' },
     { name: 'Celestone' },
     { name: 'Celexa' },
     { name: 'CellCept' },
     { name: 'Cenestin' },
     { name: 'Cephalexin' },
     { name: 'Ceritinib' },
     { name: 'Certolizumab' },
     { name: 'Cervidil' },
     { name: 'Cetirizine' },
     { name: 'Cetirizine  pseudoephedrine' },
     { name: 'Cetuximab' },
     { name: 'Cevimeline' },
     { name: 'Chantix' },
     { name: 'Chaparral' },
     { name: 'Chateal' },
     { name: 'Cheratussin AC' },
     { name: 'Childrens Claritin Allergy' },
     { name: 'Childrens Dimetapp Decongestant Infant' },
     { name: 'Childrens Motrin' },
     { name: 'ChlorTrimeton' },
     { name: 'Chloral hydrate' },
     { name: 'Chlorambucil' },
     { name: 'Chlorcyclizine  phenylephrine' },
     { name: 'Chlordiazepoxide' },
     { name: 'Chlordiazepoxide  clidinium' },
     { name: 'Chlorhexidine' },
     { name: 'Chloromycetin' },
     { name: 'Chlorpheniramine' },
     { name: 'Chlorpheniramine  dextromethorphan' },
     { name: 'Chlorpheniramine  dextromethorphan  phenylephrine' },
     { name: 'Chlorpheniramine  dextromethorphan  pseudoephedrine' },
     { name: 'Chlorpheniramine  hydrocodone' },
     { name: 'Chlorpheniramine  hydrocodone  phenylephrine' },
     { name: 'Chlorpheniramine  hydrocodone  pseudoephedrine' },
     { name: 'Chlorpheniramine  methscopolamine  pseudoephedrine' },
     { name: 'Chlorpheniramine  phenylephrine' },
     { name: 'Chlorpheniramine  pseudoephedrine' },
     { name: 'Chlorpromazine' },
     { name: 'Chlorthalidone' },
     { name: 'Chlorzoxazone' },
     { name: 'Cholestyramine' },
     { name: 'Choline salicylate  magnesium salicylate' },
     { name: 'Chondroitin  glucosamine' },
     { name: 'Chondroitin  glucosamine  methylsulfonylmethane' },
     { name: 'Chorionic gonadotropin hcg' },
     { name: 'Chromium picolinate' },
     { name: 'Cialis' },
     { name: 'Ciclesonide' },
     { name: 'Ciclopirox' },
     { name: 'Cimetidine' },
     { name: 'Cimzia' },
     { name: 'Cinacalcet' },
     { name: 'Cinryze' },
     { name: 'Cipro' },
     { name: 'Ciprodex' },
     { name: 'Ciprofloxacin' },
     { name: 'Ciprofloxacin  dexamethasone' },
     { name: 'Cisapride' },
     { name: 'Citalopram' },
     { name: 'CitraNatal 90 DHA' },
     { name: 'Citrate of Magnesia' },
     { name: 'Citric acid  magnesium oxide  sodium picosulfate' },
     { name: 'Claravis' },
     { name: 'Clarifoam EF' },
     { name: 'Clarinex' },
     { name: 'Clarithromycin' },
     { name: 'Claritin' },
     { name: 'ClaritinD' },
     { name: 'ClaritinD 12 Hour' },
     { name: 'Clear Eyes Contact Lens MultiAction Relief' },
     { name: 'ClearLax' },
     { name: 'Cleocin' },
     { name: 'Climara' },
     { name: 'Climara Pro' },
     { name: 'Clindamax' },
     { name: 'Clindamycin' },
     { name: 'Clindamycin  tretinoin' },
     { name: 'Clindesse' },
     { name: 'Clobazam' },
     { name: 'Clobetasol' },
     { name: 'Clobex' },
     { name: 'Clocortolone' },
     { name: 'Cloderm' },
     { name: 'Clomid' },
     { name: 'Clomiphene' },
     { name: 'Clomipramine' },
     { name: 'Clonazepam' },
     { name: 'Clonidine' },
     { name: 'Clopidogrel' },
     { name: 'Clorazepate' },
     { name: 'Clotrimazole' },
     { name: 'Clozapine' },
     { name: 'Clozaril' },
     { name: 'CoQ10' },
     { name: 'Coagulation factor ix' },
     { name: 'Coal tar' },
     { name: 'Coartem' },
     { name: 'Cobicistat  darunavir' },
     { name: 'Cobicistat  elvitegravir  emtricitabine  tenofovir' },
     {
          name: 'Cobicistat  elvitegravir  emtricitabine  tenofovir alafenamide',
     },
     { name: 'Codeine' },
     { name: 'Codeine  guaifenesin' },
     { name: 'Codeine  promethazine' },
     { name: 'Codimal DM' },
     { name: 'Cogentin' },
     { name: 'Colace' },
     { name: 'Colazal' },
     { name: 'Colchicine' },
     { name: 'Colcrys' },
     { name: 'Colesevelam' },
     { name: 'Collagenase Santyl' },
     { name: 'Collagenase clostridium histolyticum' },
     { name: 'Colyte' },
     { name: 'Combivent' },
     { name: 'Combivir' },
     { name: 'Commit' },
     { name: 'Compazine' },
     { name: 'Complera' },
     { name: 'ConZip' },
     { name: 'Concerta' },
     { name: 'Condylox' },
     { name: 'Conjugated estrogens' },
     { name: 'Conjugated estrogens  medroxyprogesterone' },
     { name: 'Contrave' },
     { name: 'Copaxone' },
     { name: 'Copper' },
     { name: 'Cordarone' },
     { name: 'Cordran Tape' },
     { name: 'Coreg' },
     { name: 'Coreg CR' },
     { name: 'Coricidin HBP Cold  Flu' },
     { name: 'Coricidin HBP Cough  Cold' },
     { name: 'Corlanor' },
     { name: 'Correctol' },
     { name: 'Cortef' },
     { name: 'Corticotropin' },
     { name: 'Cortisporin Otic' },
     { name: 'Cortizone10' },
     { name: 'Cosentyx' },
     { name: 'Cosopt' },
     { name: 'Cosopt PF' },
     { name: 'Coumadin' },
     { name: 'Cozaar' },
     { name: 'Creon' },
     { name: 'Crestor' },
     { name: 'Crisaborole' },
     { name: 'Crizotinib' },
     { name: 'Cromolyn' },
     { name: 'Crotamiton' },
     { name: 'Cryselle' },
     { name: 'Cutivate' },
     { name: 'Cyanocobalamin' },
     { name: 'Cyclafem 1  35' },
     { name: 'Cyclafem 7  7  7' },
     { name: 'Cyclessa' },
     { name: 'Cyclizine' },
     { name: 'Cyclobenzaprine' },
     { name: 'Cyclogyl' },
     { name: 'Cyclophosphamide' },
     { name: 'Cyclosporine' },
     { name: 'Cyklokapron' },
     { name: 'Cylert' },
     { name: 'Cymbalta' },
     { name: 'Cyproheptadine' },
     { name: 'Cyred' },
     { name: 'Cytomel' },
     { name: 'DDAVP' },
     { name: 'DDAVP Rhinal Tube' },
     { name: 'DHE 45' },
     { name: 'Dabigatran' },
     { name: 'Daclatasvir' },
     { name: 'Daklinza' },
     { name: 'Dalfampridine' },
     { name: 'Daliresp' },
     { name: 'Dallergy' },
     { name: 'Dalmane' },
     { name: 'Danocrine' },
     { name: 'Dapagliflozin' },
     { name: 'Dapagliflozin  metformin' },
     { name: 'Dapsone' },
     { name: 'Darbepoetin alfa' },
     { name: 'Darifenacin' },
     { name: 'Darunavir' },
     { name: 'Darvon' },
     { name: 'Dasabuvir  ombitasvir  paritaprevir  ritonavir' },
     { name: 'Dasatinib' },
     { name: 'Dasetta 7  7  7' },
     { name: 'Daypro' },
     { name: 'Daytrana' },
     { name: 'Deblitane' },
     { name: 'Debrox' },
     { name: 'Decadron' },
     { name: 'Deconamine' },
     { name: 'Degarelix' },
     { name: 'Delatestryl' },
     { name: 'Delsym' },
     { name: 'Delsym 12 Hour Cough Relief' },
     { name: 'Deltasone' },
     { name: 'Demadex' },
     { name: 'Demerol' },
     { name: 'Denavir' },
     { name: 'Denosumab' },
     { name: 'Deoxycholic acid' },
     { name: 'Depakote' },
     { name: 'Depakote ER' },
     { name: 'Deplin' },
     { name: 'DepoMedrol' },
     { name: 'DepoProvera' },
     { name: 'DepoProvera Contraceptive' },
     { name: 'DepoTestosterone' },
     { name: 'DermaSmoothe  FS Scalp' },
     { name: 'Dermal filler' },
     { name: 'Dermatop' },
     { name: 'DesOwen' },
     { name: 'Desipramine' },
     { name: 'Desloratadine' },
     { name: 'Desmopressin' },
     { name: 'Desogen' },
     { name: 'Desogestrel  ethinyl estradiol' },
     { name: 'Desonide' },
     { name: 'Desoximetasone' },
     { name: 'Desoxyn' },
     { name: 'DesquamX Wash' },
     { name: 'Desvenlafaxine' },
     { name: 'Desyrel' },
     { name: 'Detrol' },
     { name: 'Detrol LA' },
     { name: 'Dexamethasone' },
     { name: 'Dexamethasone  neomycin  polymyxin b' },
     { name: 'Dexamethasone Intensol' },
     { name: 'Dexbrompheniramine  pseudoephedrine' },
     { name: 'Dexchlorpheniramine' },
     { name: 'Dexedrine' },
     { name: 'Dexilant' },
     { name: 'Dexlansoprazole' },
     { name: 'Dexmethylphenidate' },
     { name: 'Dextroamphetamine' },
     { name: 'Dextromethorphan' },
     { name: 'Dextromethorphan  guaifenesin' },
     { name: 'Dextromethorphan  guaifenesin  phenylephrine' },
     { name: 'Dextromethorphan  guaifenesin  pseudoephedrine' },
     { name: 'Dextromethorphan  phenylephrine  pyrilamine' },
     { name: 'Dextromethorphan  promethazine' },
     { name: 'Dextromethorphan  quinidine' },
     { name: 'Dextrostat' },
     { name: 'DiGel' },
     { name: 'Diamox' },
     { name: 'Diamox Sequels' },
     { name: 'Diazepam' },
     { name: 'Diazepam Intensol' },
     { name: 'Diclegis' },
     { name: 'Diclofenac' },
     { name: 'Diclofenac  misoprostol' },
     { name: 'Dicyclomine' },
     { name: 'Didrex' },
     { name: 'Dienogest  estradiol' },
     { name: 'Diethylpropion' },
     { name: 'Differin' },
     { name: 'Dificid' },
     { name: 'Diflorasone' },
     { name: 'Diflucan' },
     { name: 'Difluprednate' },
     { name: 'Digoxin' },
     { name: 'Dihydroergotamine' },
     { name: 'Dilantin' },
     { name: 'Dilaudid' },
     { name: 'DilaudidHP' },
     { name: 'Diltiazem' },
     { name: 'Dimenhydrinate' },
     { name: 'Dimetapp Childrens Cold  Cough' },
     { name: 'Dimethyl fumarate' },
     { name: 'Dinoprostone' },
     { name: 'Diovan' },
     { name: 'Diovan HCT' },
     { name: 'Diphenhydramine' },
     { name: 'Diphenhydramine  ibuprofen' },
     { name: 'Diphenhydramine  naproxen' },
     { name: 'Diprivan' },
     { name: 'Disalcid' },
     { name: 'Disopyramide' },
     { name: 'Disulfiram' },
     { name: 'Ditropan' },
     { name: 'Divalproex sodium' },
     { name: 'Divigel' },
     { name: 'Doans Pills Extra Strength' },
     { name: 'Dobutamine' },
     { name: 'Docosanol' },
     { name: 'Docusate  senna' },
     { name: 'Dofetilide' },
     { name: 'Dolobid' },
     { name: 'Dolophine' },
     { name: 'Dolutegravir' },
     { name: 'Donepezil' },
     { name: 'Donnatal' },
     { name: 'Doral' },
     { name: 'Doribax' },
     { name: 'Doripenem' },
     { name: 'Doryx' },
     { name: 'Dorzolamide  timolol' },
     { name: 'Dovonex' },
     { name: 'Doxazosin' },
     { name: 'Doxepin' },
     { name: 'Doxidan Tablet' },
     { name: 'Doxorubicin' },
     { name: 'Doxy 100' },
     { name: 'Doxycycline' },
     { name: 'Doxylamine' },
     { name: 'Doxylamine  pyridoxine' },
     { name: 'Dramamine' },
     { name: 'Drixoral Cold and Allergy' },
     { name: 'Drixoral Decongestant NonDrowsy' },
     { name: 'Dronabinol' },
     { name: 'Dronedarone' },
     { name: 'Droperidol' },
     { name: 'Drospirenone  estradiol' },
     { name: 'Drospirenone  ethinyl estradiol' },
     { name: 'Drospirenone  ethinyl estradiol  levomefolate calcium' },
     { name: 'Drysol' },
     { name: 'Duac' },
     { name: 'Duavee' },
     { name: 'Duexis' },
     { name: 'Dulaglutide' },
     { name: 'Dulcolax' },
     { name: 'Dulcolax Laxative' },
     { name: 'Dulera' },
     { name: 'Duloxetine' },
     { name: 'Duofilm' },
     { name: 'Dupilumab' },
     { name: 'Dupixent' },
     { name: 'Duragesic' },
     { name: 'Durezol' },
     { name: 'Dutasteride' },
     { name: 'Dutasteride  tamsulosin' },
     { name: 'Dyanavel XR' },
     { name: 'Dyazide' },
     { name: 'Dymista' },
     { name: 'DynaCirc CR' },
     { name: 'Dyrenium' },
     { name: 'EES400' },
     { name: 'EZGas II' },
     { name: 'Echinacea' },
     { name: 'Econazole' },
     { name: 'Edarbi' },
     { name: 'Edarbyclor' },
     { name: 'Edecrin' },
     { name: 'Edex' },
     { name: 'Edluar' },
     { name: 'Edoxaban' },
     { name: 'Efavirenz' },
     { name: 'Efavirenz  emtricitabine  tenofovir' },
     { name: 'Effexor' },
     { name: 'Effexor XR' },
     { name: 'Efinaconazole' },
     { name: 'Eflornithine' },
     { name: 'Efudex' },
     { name: 'Egrifta' },
     { name: 'Elavil' },
     { name: 'Elbasvir  grazoprevir' },
     { name: 'Eldepryl' },
     { name: 'Elestrin' },
     { name: 'Eletone' },
     { name: 'Eletriptan' },
     { name: 'Elidel' },
     { name: 'Eligard' },
     { name: 'Eliquis' },
     { name: 'Elmiron' },
     { name: 'Elocon' },
     { name: 'Eltrombopag' },
     { name: 'Eluxadoline' },
     { name: 'Embeda' },
     { name: 'Emend' },
     { name: 'Emetrol' },
     { name: 'Emollients' },
     { name: 'Emoquette' },
     { name: 'Empagliflozin' },
     { name: 'Empagliflozin  linagliptin' },
     { name: 'Empagliflozin  metformin' },
     { name: 'Emsam' },
     { name: 'Emtricitabine  rilpivirine  tenofovir' },
     { name: 'Emtricitabine  tenofovir' },
     { name: 'Enablex' },
     { name: 'Enalapril' },
     { name: 'Enbrel' },
     { name: 'Endocet' },
     { name: 'Enfuvirtide' },
     { name: 'Enjuvia' },
     { name: 'Enoxaparin' },
     { name: 'Enskyce' },
     { name: 'Entacapone' },
     { name: 'EnteraGam' },
     { name: 'Entocort EC' },
     { name: 'Entresto' },
     { name: 'Entyvio' },
     { name: 'Eovist' },
     { name: 'Epclusa' },
     { name: 'Ephedrine' },
     { name: 'EpiCeram' },
     { name: 'Epiduo' },
     { name: 'Epiduo Forte' },
     { name: 'Epinephrine' },
     { name: 'Eplerenone' },
     { name: 'Epoetin alfa' },
     { name: 'Epogen' },
     { name: 'Epoprostenol' },
     { name: 'Epsom Salt' },
     { name: 'Eptifibatide' },
     { name: 'Epzicom' },
     { name: 'Equetro' },
     { name: 'Ergocalciferol' },
     { name: 'Eribulin' },
     { name: 'Erlotinib' },
     { name: 'Errin' },
     { name: 'Ertaczo' },
     { name: 'Erythrocin' },
     { name: 'Erythromycin' },
     { name: 'Escitalopram' },
     { name: 'Esgic' },
     { name: 'EsgicPlus' },
     { name: 'Eskalith' },
     { name: 'Eslicarbazepine' },
     { name: 'Esomeprazole' },
     { name: 'Esomeprazole  naproxen' },
     { name: 'Estarylla' },
     { name: 'Estazolam' },
     { name: 'Esterified estrogens' },
     { name: 'Esterified estrogens  methyltestosterone' },
     { name: 'Estrace' },
     { name: 'Estrace Vaginal Cream' },
     { name: 'Estraderm' },
     { name: 'Estradiol' },
     { name: 'Estradiol  levonorgestrel' },
     { name: 'Estradiol  norethindrone' },
     { name: 'Estradiol Patch' },
     { name: 'Estratest HS' },
     { name: 'Estring' },
     { name: 'Estropipate' },
     { name: 'Eszopiclone' },
     { name: 'Etanercept' },
     { name: 'Ethambutol' },
     { name: 'Ethinyl estradiol  ethynodiol' },
     { name: 'Ethinyl estradiol  etonogestrel' },
     { name: 'Ethinyl estradiol  folic acid  levonorgestrel' },
     { name: 'Ethinyl estradiol  levonorgestrel' },
     { name: 'Ethinyl estradiol  norelgestromin' },
     { name: 'Ethinyl estradiol  norethindrone' },
     { name: 'Ethinyl estradiol  norgestimate' },
     { name: 'Ethinyl estradiol  norgestrel' },
     { name: 'Ethmozine' },
     { name: 'Ethotoin' },
     { name: 'Etodolac' },
     { name: 'Etonogestrel' },
     { name: 'Eucrisa' },
     { name: 'Euflexxa' },
     { name: 'Evamist' },
     { name: 'Evekeo' },
     { name: 'Evening Primrose Oil' },
     { name: 'Everolimus' },
     { name: 'Evista' },
     { name: 'Evolocumab' },
     { name: 'Evoxac' },
     { name: 'Evzio' },
     { name: 'ExLax Regular Strength Pills' },
     { name: 'Exalgo' },
     { name: 'Excedrin' },
     { name: 'Excedrin Back  Body' },
     { name: 'Excedrin PM' },
     { name: 'Excedrin Quick Tab' },
     { name: 'Excedrin Tension Headache' },
     { name: 'Exelon' },
     { name: 'Exemestane' },
     { name: 'Exenatide' },
     { name: 'Exforge' },
     { name: 'Exforge HCT' },
     { name: 'Exparel' },
     { name: 'Exubera' },
     { name: 'Eyebright' },
     { name: 'Eylea' },
     { name: 'Ezetimibe' },
     { name: 'Ezetimibe  simvastatin' },
     { name: 'Factive' },
     { name: 'Falmina' },
     { name: 'Famciclovir' },
     { name: 'Famotidine' },
     { name: 'Famotidine  ibuprofen' },
     { name: 'Famvir' },
     { name: 'Fanapt' },
     { name: 'Farxiga' },
     { name: 'Fastin' },
     { name: 'Febuxostat' },
     { name: 'FeenAMint' },
     { name: 'Felbamate' },
     { name: 'Felbatol' },
     { name: 'Feldene' },
     { name: 'Felodipine' },
     { name: 'Femara' },
     { name: 'Femcon Fe' },
     { name: 'Femring' },
     { name: 'Fenofibrate' },
     { name: 'Fenofibric acid' },
     { name: 'Fenoprofen' },
     { name: 'Fentanyl' },
     { name: 'Fentanyl Transdermal System' },
     { name: 'Fentora' },
     { name: 'Fenugreek' },
     { name: 'Feosol Original' },
     { name: 'Feraheme' },
     { name: 'Ferric citrate' },
     { name: 'Ferrous fumarate  iron polysaccharide' },
     { name: 'Ferrous gluconate' },
     { name: 'Ferrous sulfate' },
     { name: 'Fesoterodine' },
     { name: 'Fetzima' },
     { name: 'Fexofenadine' },
     { name: 'Fexofenadine  pseudoephedrine' },
     { name: 'FiberCon' },
     { name: 'Fidaxomicin' },
     { name: 'Finacea' },
     { name: 'Finasteride' },
     { name: 'Fingolimod' },
     { name: 'Fioricet' },
     { name: 'Fioricet with Codeine' },
     { name: 'Fiorinal' },
     { name: 'Fiorinal with Codeine' },
     { name: 'Firazyr' },
     { name: 'Flagyl' },
     { name: 'Flagyl ER' },
     { name: 'Flagyl IV' },
     { name: 'Flavoxate' },
     { name: 'Flecainide' },
     { name: 'Flector Patch' },
     { name: 'Fleet Bisacodyl' },
     { name: 'Fleet Enema' },
     { name: 'Fleet Phospho Soda' },
     { name: 'Flexeril' },
     { name: 'Flolan' },
     { name: 'Flomax' },
     { name: 'Flonase' },
     { name: 'Flonase Sensimist' },
     { name: 'Florastor' },
     { name: 'Florinef' },
     { name: 'Florinef Acetate' },
     { name: 'Flovent' },
     { name: 'Flovent HFA' },
     { name: 'FluMist' },
     { name: 'Fluconazole' },
     { name: 'Fludrocortisone' },
     { name: 'Flunisolide' },
     { name: 'Fluocinolone' },
     { name: 'Fluocinolone  hydroquinone  tretinoin' },
     { name: 'Fluocinonide' },
     { name: 'Fluoride' },
     { name: 'Fluorometholone' },
     { name: 'Fluoroplex' },
     { name: 'Fluorouracil' },
     { name: 'Fluoxetine' },
     { name: 'Fluoxetine  olanzapine' },
     { name: 'Fluphenazine' },
     { name: 'Flurandrenolide' },
     { name: 'Flurazepam' },
     { name: 'Flurbiprofen' },
     { name: 'Fluticasone' },
     { name: 'Fluticasone  salmeterol' },
     { name: 'Fluticasone  vilanterol' },
     { name: 'Fluvoxamine' },
     { name: 'Focalin' },
     { name: 'Focalin XR' },
     { name: 'Follicle stimulating hormone' },
     { name: 'Foradil Aerolizer' },
     { name: 'Forfivo XL' },
     { name: 'Formoterol' },
     { name: 'Formoterol  mometasone' },
     { name: 'Forteo' },
     { name: 'Fortesta' },
     { name: 'Fosamax' },
     { name: 'Fosinopril' },
     { name: 'Fosrenol' },
     { name: 'FreshKote' },
     { name: 'Frova' },
     { name: 'Frovatriptan' },
     { name: 'Fulvestrant' },
     { name: 'Fulvicin U  F' },
     { name: 'Furadantin' },
     { name: 'Furosemide' },
     { name: 'Fycompa' },
     { name: 'Gabapentin' },
     { name: 'Gabapentin enacarbil' },
     { name: 'Gabarone' },
     { name: 'Gabitril' },
     { name: 'Gadoxetate disodium' },
     { name: 'Galantamine' },
     { name: 'Gamunex' },
     { name: 'GamunexC' },
     { name: 'Gardasil' },
     { name: 'Garlic' },
     { name: 'GasX' },
     { name: 'Gatifloxacin' },
     { name: 'GaviLyteC' },
     { name: 'GaviLyteG' },
     { name: 'GaviLyteN' },
     { name: 'Gefitinib' },
     { name: 'Gelnique' },
     { name: 'Gemfibrozil' },
     { name: 'Gemifloxacin' },
     { name: 'GenTeal' },
     { name: 'Generess Fe' },
     { name: 'Generlac' },
     { name: 'Gentamicin' },
     { name: 'Gentian violet' },
     { name: 'Genvoya' },
     { name: 'Geodon' },
     { name: 'Gianvi' },
     { name: 'Gildess Fe 1  20' },
     { name: 'Gildess Fe 15  30' },
     { name: 'Gilenya' },
     { name: 'Ginger' },
     { name: 'Ginseng' },
     { name: 'Glatiramer' },
     { name: 'Gleevec' },
     { name: 'Glimepiride' },
     { name: 'Glimepiride  rosiglitazone' },
     { name: 'GlipiZIDE XL' },
     { name: 'Glipizide' },
     { name: 'Glucophage' },
     { name: 'Glucophage XR' },
     { name: 'Glucose' },
     { name: 'Glucotrol' },
     { name: 'Glyburide' },
     { name: 'Glyburide  metformin' },
     { name: 'Glycerin' },
     { name: 'Glyxambi' },
     { name: 'GoLYTELY' },
     { name: 'Gold sodium thiomalate' },
     { name: 'Golimumab' },
     { name: 'Gonalf' },
     { name: 'Goodys ExtraStrength Headache Powders' },
     { name: 'Goserelin' },
     { name: 'Gralise' },
     { name: 'Granulex' },
     { name: 'GrisPEG' },
     { name: 'Griseofulvin' },
     { name: 'Guaifenesin' },
     { name: 'Guaifenesin  hydrocodone' },
     { name: 'Guaifenesin  phenylephrine' },
     { name: 'Guaifenesin  pseudoephedrine' },
     { name: 'Guanfacine' },
     { name: 'Guarana' },
     { name: 'Gynazole1' },
     { name: 'HP Acthar Gel' },
     { name: 'Habitrol' },
     { name: 'Halaven' },
     { name: 'Halcion' },
     { name: 'Haldol' },
     { name: 'HalfLytely and Bisacodyl' },
     { name: 'Halfan' },
     { name: 'Halobetasol' },
     { name: 'Halofantrine' },
     { name: 'Haloperidol' },
     { name: 'Harvoni' },
     { name: 'Heme iron polypeptide' },
     { name: 'Herceptin' },
     { name: 'Hetlioz' },
     { name: 'Hexachlorophene' },
     { name: 'Hiprex' },
     { name: 'Histrelin' },
     { name: 'Hizentra' },
     { name: 'Homatropine  hydrocodone' },
     { name: 'Horizant' },
     { name: 'Humalog' },
     { name: 'Humalog KwikPen' },
     { name: 'Human papillomavirus vaccine' },
     { name: 'Humira' },
     { name: 'Humulin N' },
     { name: 'Humulin R U500 Concentrated' },
     { name: 'Hyaluronan' },
     { name: 'Hycodan' },
     { name: 'Hydralazine' },
     { name: 'Hydrea' },
     { name: 'Hydrochlorothiazide' },
     { name: 'Hydrochlorothiazide  irbesartan' },
     { name: 'Hydrochlorothiazide  lisinopril' },
     { name: 'Hydrochlorothiazide  losartan' },
     { name: 'Hydrochlorothiazide  olmesartan' },
     { name: 'Hydrochlorothiazide  telmisartan' },
     { name: 'Hydrochlorothiazide  triamterene' },
     { name: 'Hydrochlorothiazide  valsartan' },
     { name: 'Hydrocodone' },
     { name: 'Hydrocodone  ibuprofen' },
     { name: 'Hydrocodone  pseudoephedrine' },
     { name: 'Hydrocortisone' },
     { name: 'Hydrocortisone  neomycin  polymyxin b' },
     { name: 'Hydrocortisone  pramoxine' },
     { name: 'Hydromet' },
     { name: 'Hydromorphone' },
     { name: 'Hydroquinone' },
     { name: 'Hydroxocobalamin' },
     { name: 'Hydroxyamphetamine  tropicamide' },
     { name: 'Hydroxychloroquine' },
     { name: 'Hydroxyprogesterone' },
     { name: 'Hydroxyurea' },
     { name: 'Hydroxyzine' },
     { name: 'Hylan gf 20' },
     { name: 'Hylenex' },
     { name: 'Hyoscyamine' },
     {
          name: 'Hyoscyamine  methenamine  methylene blue  phenyl salicylate',
     },
     {
          name: 'Hyoscyamine  methenamine  methylene blue  phenyl salicylate  sodium biphosphate',
     },
     { name: 'Hyosyne' },
     { name: 'Hypercare' },
     { name: 'Hysingla ER' },
     { name: 'Hytrin' },
     { name: 'Hyzaar' },
     { name: 'Hyzine' },
     { name: 'Ibandronate' },
     { name: 'Ibrance' },
     { name: 'Ibrutinib' },
     { name: 'Ibuprofen' },
     { name: 'Ibuprofen  pseudoephedrine' },
     { name: 'Icatibant' },
     { name: 'Icosapent' },
     { name: 'Ilevro' },
     { name: 'Iloperidone' },
     { name: 'Imatinib' },
     { name: 'Imbruvica' },
     { name: 'Imdur' },
     { name: 'Imipramine' },
     { name: 'Imiquimod' },
     { name: 'Imitrex' },
     { name: 'Imitrex Nasal' },
     { name: 'Imitrex Statdose' },
     { name: 'Immune globulin intravenous' },
     { name: 'Immune globulin intravenous and subcutaneous' },
     { name: 'Immune globulin subcutaneous' },
     { name: 'Imodium' },
     { name: 'Imodium AD' },
     { name: 'Implanon' },
     { name: 'Imuran' },
     { name: 'Inapsine' },
     { name: 'Incivek' },
     { name: 'Incruse Ellipta' },
     { name: 'Inderal' },
     { name: 'Inderal LA' },
     { name: 'Indocin' },
     { name: 'Indocin SR' },
     { name: 'Indomethacin' },
     { name: 'Infliximab' },
     { name: 'Influenza virus vaccine inactivated' },
     { name: 'Influenza virus vaccine live trivalent' },
     { name: 'Inova 4  1' },
     { name: 'Insulin aspart' },
     { name: 'Insulin aspart  insulin degludec' },
     { name: 'Insulin degludec' },
     { name: 'Insulin detemir' },
     { name: 'Insulin glargine' },
     { name: 'Insulin glulisine' },
     { name: 'Insulin inhalation rapid acting' },
     { name: 'Insulin isophane' },
     { name: 'Insulin isophane  insulin regular' },
     { name: 'Insulin lispro' },
     { name: 'Insulin regular' },
     { name: 'Intal' },
     { name: 'Intelence' },
     { name: 'Interferon alfa2b' },
     { name: 'Interferon beta1a' },
     { name: 'Interferon beta1b' },
     { name: 'Intron A' },
     { name: 'Intuniv' },
     { name: 'Invega' },
     { name: 'Invega Sustenna' },
     { name: 'Invega Trinza' },
     { name: 'Invokana' },
     { name: 'IophenC NR' },
     { name: 'Ipratropium' },
     { name: 'Irbesartan' },
     { name: 'Iressa' },
     { name: 'Iron polysaccharide' },
     { name: 'Iron sucrose' },
     { name: 'Isentress' },
     { name: 'Isoniazid' },
     { name: 'Isoproterenol' },
     { name: 'Isosorbide mononitrate' },
     { name: 'Isotretinoin' },
     { name: 'Itraconazole' },
     { name: 'Ivacaftor' },
     { name: 'Ivermectin' },
     { name: 'Ixekizumab' },
     { name: 'Jakafi' },
     { name: 'Jalyn' },
     { name: 'Janumet' },
     { name: 'Januvia' },
     { name: 'Jardiance' },
     { name: 'Jencycla' },
     { name: 'Jentadueto' },
     { name: 'Jolessa' },
     { name: 'Jolivette' },
     { name: 'Jublia' },
     { name: 'Junel 1  20' },
     { name: 'Junel Fe 1  20' },
     { name: 'Junel Fe 15  30' },
     { name: 'Junel Fe 24' },
     { name: 'Kadian' },
     { name: 'Kalbitor' },
     { name: 'Kaletra' },
     { name: 'Kalydeco' },
     { name: 'Kapidex' },
     { name: 'Kapvay' },
     { name: 'Kariva' },
     { name: 'Kava' },
     { name: 'Keflex' },
     { name: 'Kemadrin' },
     { name: 'Kenalog' },
     { name: 'Kenalog10' },
     { name: 'Kenalog40' },
     { name: 'Keppra' },
     { name: 'Keppra XR' },
     { name: 'Kerafoam' },
     { name: 'Kerydin' },
     { name: 'Ketamine' },
     { name: 'Ketoconazole' },
     { name: 'Ketoprofen' },
     { name: 'Ketorolac' },
     { name: 'Ketotifen' },
     { name: 'Keytruda' },
     { name: 'Kineret' },
     { name: 'Kionex' },
     { name: 'Klonopin' },
     { name: 'Klonopin Wafer' },
     { name: 'KlorCon' },
     { name: 'KneeRelief' },
     { name: 'Kombiglyze XR' },
     { name: 'Konsyl' },
     { name: 'Krystexxa' },
     { name: 'Kyleena' },
     { name: 'Kyprolis' },
     { name: 'LacHydrin' },
     { name: 'Lacosamide' },
     { name: 'Lacrisert' },
     { name: 'Lactaid Ultra' },
     { name: 'Lactase' },
     { name: 'Lactic acid' },
     { name: 'Lactobacillus acidophilus' },
     { name: 'Lactulose' },
     { name: 'Lamictal' },
     { name: 'Lamisil' },
     { name: 'Lamisil AT' },
     { name: 'Lamivudine  zidovudine' },
     { name: 'Lamotrigine' },
     { name: 'Lansoprazole' },
     { name: 'Lantus' },
     { name: 'Lantus Solostar' },
     { name: 'Lapatinib' },
     { name: 'Lariam' },
     { name: 'Larin Fe 1  20' },
     { name: 'Larin Fe 15  30' },
     { name: 'Lasix' },
     { name: 'Lastacaft' },
     { name: 'Latanoprost' },
     { name: 'Latisse' },
     { name: 'Latuda' },
     { name: 'Ledipasvir  sofosbuvir' },
     { name: 'Leflunomide' },
     { name: 'Lemtrada' },
     { name: 'Lenalidomide' },
     { name: 'Lesinurad' },
     { name: 'Lessina' },
     { name: 'Letairis' },
     { name: 'Letrozole' },
     { name: 'Leuprolide' },
     { name: 'Levacet' },
     { name: 'Levalbuterol' },
     { name: 'Levaquin' },
     { name: 'Levemir' },
     { name: 'Levetiracetam' },
     { name: 'Levitra' },
     { name: 'Levlen' },
     { name: 'LevoDromoran' },
     { name: 'Levocarnitine' },
     { name: 'Levocetirizine' },
     { name: 'Levofloxacin' },
     { name: 'Levomilnacipran' },
     { name: 'Levonorgestrel' },
     { name: 'Levophed' },
     { name: 'Levora' },
     { name: 'Levorphanol' },
     { name: 'Levothyroxine' },
     { name: 'Levoxyl' },
     { name: 'Levsin' },
     { name: 'Levsin SL' },
     { name: 'Lexapro' },
     { name: 'Lexiscan' },
     { name: 'Lialda' },
     { name: 'Librax' },
     { name: 'Librium' },
     { name: 'Lidex' },
     { name: 'Lidocaine' },
     { name: 'Lidocaine  menthol' },
     { name: 'Lidocaine  prilocaine' },
     { name: 'Lidocaine Viscous' },
     { name: 'Lidoderm' },
     { name: 'Lifitegrast' },
     { name: 'Liletta' },
     { name: 'Limbitrol DS' },
     { name: 'Limbrel' },
     { name: 'Linaclotide' },
     { name: 'Linagliptin' },
     { name: 'Lindane' },
     { name: 'Linezolid' },
     { name: 'Linzess' },
     { name: 'Lioresal' },
     { name: 'Liothyronine' },
     { name: 'Lipitor' },
     { name: 'Liraglutide' },
     { name: 'Lisdexamfetamine' },
     { name: 'Lisinopril' },
     { name: 'Lithium' },
     { name: 'Lithobid' },
     { name: 'Livalo' },
     { name: 'Lmethylfolate' },
     { name: 'Lo  Ovral' },
     { name: 'Lo  Ovral28' },
     { name: 'Lo Loestrin Fe' },
     { name: 'LoSeasonique' },
     { name: 'Locoid Lipocream' },
     { name: 'Lodine' },
     { name: 'Loestrin 21 1  20' },
     { name: 'Loestrin 24 Fe' },
     { name: 'Loestrin Fe 1  20' },
     { name: 'Lomaira' },
     { name: 'Lomedia 24 Fe' },
     { name: 'Lomotil' },
     { name: 'Lonox' },
     { name: 'Loperamide' },
     { name: 'Lopressor' },
     { name: 'Loprox' },
     { name: 'Loratadine' },
     { name: 'Loratadine  pseudoephedrine' },
     { name: 'Lorazepam' },
     { name: 'Lorazepam Intensol' },
     { name: 'Lorcaserin' },
     { name: 'Lortab' },
     { name: 'Loryna' },
     { name: 'Lorzone' },
     { name: 'Losartan' },
     { name: 'Lotemax' },
     { name: 'Loteprednol  tobramycin' },
     { name: 'Lotrel' },
     { name: 'Lotronex' },
     { name: 'Lovastatin' },
     { name: 'Lovastatin  niacin' },
     { name: 'Lovaza' },
     { name: 'Lovenox' },
     { name: 'LowOgestrel21' },
     { name: 'Loxapine' },
     { name: 'Lubiprostone' },
     { name: 'Lucentis' },
     { name: 'Lumigan' },
     { name: 'Luminal' },
     { name: 'Lunesta' },
     { name: 'Lupron' },
     { name: 'Lupron Depot' },
     { name: 'Lupron DepotPED' },
     { name: 'Lurasidone' },
     { name: 'Lutera' },
     { name: 'Luvox' },
     { name: 'Luvox CR' },
     { name: 'Luxiq' },
     { name: 'Lybrel' },
     { name: 'Lymphoseek' },
     { name: 'Lyrica' },
     { name: 'Lysine' },
     { name: 'Lysteda' },
     { name: 'Lyza' },
     { name: 'MG217 Medicated Tar' },
     { name: 'MS Contin' },
     { name: 'Macitentan' },
     { name: 'Macrobid' },
     { name: 'Macrodantin' },
     { name: 'Magaldrate  simethicone' },
     { name: 'Magnacet' },
     { name: 'Magnesium amino acids chelate' },
     { name: 'Magnesium aspartate' },
     { name: 'Magnesium citrate' },
     { name: 'Magnesium hydroxide' },
     { name: 'Magnesium oxide' },
     { name: 'Magnesium salicylate' },
     { name: 'Magnesium sulfate' },
     { name: 'Magnesium sulfate  potassium sulfate  sodium sulfate' },
     { name: 'Makena' },
     { name: 'Malarone' },
     { name: 'Malathion' },
     { name: 'Maprotiline' },
     { name: 'Marezine' },
     { name: 'Marinol' },
     { name: 'Marlissa' },
     { name: 'Maxalt' },
     { name: 'MaxaltMLT' },
     { name: 'Maxaron Forte' },
     { name: 'Maxifed DM' },
     { name: 'Mebaral' },
     { name: 'Meclizine' },
     { name: 'Medrol Dosepak' },
     { name: 'Medrox' },
     { name: 'Medroxyprogesterone' },
     { name: 'Mefenamic acid' },
     { name: 'Mefloquine' },
     { name: 'Megace' },
     { name: 'Megace ES' },
     { name: 'Megestrol' },
     { name: 'Melatonin' },
     { name: 'Meloxicam' },
     { name: 'Memantine' },
     { name: 'Meningococcal conjugate vaccine' },
     { name: 'Menopur' },
     { name: 'Menotropins' },
     { name: 'Menthol  zinc oxide' },
     { name: 'Meperidine' },
     { name: 'Mephobarbital' },
     { name: 'Mepolizumab' },
     { name: 'Meprobamate' },
     { name: 'Mercaptopurine' },
     { name: 'Meridia' },
     { name: 'Mesalamine' },
     { name: 'Mestinon' },
     { name: 'Mestranol  norethindrone' },
     { name: 'Metadate CD' },
     { name: 'Metadate ER' },
     { name: 'Metamucil' },
     { name: 'Metaproterenol' },
     { name: 'Metaxalone' },
     { name: 'Metformin' },
     { name: 'Metformin  saxagliptin' },
     { name: 'Metformin  sitagliptin' },
     { name: 'Methadone' },
     { name: 'Methadone Diskets' },
     { name: 'Methadose' },
     { name: 'Methamphetamine' },
     { name: 'Methenamine' },
     { name: 'Methergine' },
     { name: 'Methimazole' },
     { name: 'Methocarbamol' },
     { name: 'Methotrexate' },
     { name: 'Methscopolamine' },
     { name: 'Methyl salicylate' },
     { name: 'Methyldopa' },
     { name: 'Methylergonovine' },
     { name: 'Methylin' },
     { name: 'Methylin ER' },
     { name: 'Methylnaltrexone' },
     { name: 'Methylphenidate' },
     { name: 'Methylprednisolone' },
     { name: 'Metoclopramide' },
     { name: 'Metolazone' },
     { name: 'Metoprolol' },
     { name: 'Metoprolol Tartrate' },
     { name: 'Metozolv ODT' },
     { name: 'MetroCream' },
     { name: 'MetroGel' },
     { name: 'MetroGelVaginal' },
     { name: 'Metronidazole' },
     { name: 'Mevacor' },
     { name: 'Mexiletine' },
     { name: 'Miacalcin Nasal' },
     { name: 'Mibelas 24 Fe' },
     { name: 'Micardis' },
     { name: 'Micardis HCT' },
     { name: 'Miconazole' },
     { name: 'Miconazole  zinc oxide' },
     { name: 'Microgestin 1  20' },
     { name: 'Microgestin 15  30' },
     { name: 'Microgestin Fe 1  20' },
     { name: 'Microgestin Fe 15  30' },
     { name: 'Microzide' },
     { name: 'Midazolam' },
     { name: 'Midodrine' },
     { name: 'Migergot' },
     { name: 'Miglitol' },
     { name: 'Migranal' },
     { name: 'Milk of Magnesia' },
     { name: 'Milk thistle' },
     { name: 'Milnacipran' },
     { name: 'Miltown' },
     { name: 'Mimvey' },
     { name: 'Minastrin 24 Fe' },
     { name: 'Minipress' },
     { name: 'Minivelle' },
     { name: 'Minocin' },
     { name: 'Minocycline' },
     { name: 'Minoxidil' },
     { name: 'MiraLax' },
     { name: 'Mirabegron' },
     { name: 'Mirapex' },
     { name: 'Mircette' },
     { name: 'Mirena' },
     { name: 'Mirtazapine' },
     { name: 'Mirvaso' },
     { name: 'Misoprostol' },
     { name: 'Mobic' },
     { name: 'Modafinil' },
     { name: 'Moderiba' },
     { name: 'Mometasone' },
     { name: 'Monistat 1Day or Night Combination Pack' },
     { name: 'Monistat 3Day Combination Pack' },
     { name: 'Monistat 7' },
     { name: 'Monistat 7Day Combination Pack' },
     { name: 'MonoLinyah' },
     { name: 'Monodox' },
     { name: 'Mononessa' },
     { name: 'Montelukast' },
     { name: 'Monurol' },
     { name: 'Morphine' },
     { name: 'Morphine  naltrexone' },
     { name: 'Motofen' },
     { name: 'Motrin' },
     { name: 'Motrin IB' },
     { name: 'Motrin Infant Drops' },
     { name: 'Movantik' },
     { name: 'MoviPrep' },
     { name: 'Moxatag' },
     { name: 'Moxeza' },
     { name: 'Moxifloxacin' },
     { name: 'Mucinex' },
     { name: 'Mucinex D' },
     { name: 'Mucinex D Maximum Strength' },
     { name: 'Mucinex DM' },
     { name: 'Mucinex FastMax Severe Congestion  Cough' },
     { name: 'Mucomyst10' },
     { name: 'Multaq' },
     { name: 'Multivitamin' },
     { name: 'Multivitamin prenatal' },
     { name: 'Multivitamin with iron' },
     { name: 'Multivitamin with minerals' },
     { name: 'Mupirocin' },
     { name: 'Muse' },
     { name: 'My Way' },
     { name: 'Mycolog II' },
     { name: 'Mycophenolate mofetil' },
     { name: 'Mycophenolic acid' },
     { name: 'Mydayis' },
     { name: 'Myobloc' },
     { name: 'Myophen' },
     { name: 'Myrbetriq' },
     { name: 'Mysoline' },
     { name: 'NP Thyroid' },
     { name: 'Nabumetone' },
     { name: 'Nadolol' },
     { name: 'Nafcillin' },
     { name: 'Naftifine' },
     { name: 'Naftin' },
     { name: 'Nalbuphine' },
     { name: 'Naloxegol' },
     { name: 'Naloxone' },
     { name: 'Naloxone  pentazocine' },
     { name: 'Naltrexone' },
     { name: 'Namenda' },
     { name: 'Naphazoline' },
     { name: 'Naphazoline  pheniramine' },
     { name: 'Naprelan' },
     { name: 'Naprosyn' },
     { name: 'Naproxen' },
     { name: 'Naproxen  sumatriptan' },
     { name: 'Naratriptan' },
     { name: 'Narcan Injection' },
     { name: 'Nardil' },
     { name: 'Nasacort' },
     { name: 'Nasacort Allergy 24HR' },
     { name: 'Nasonex' },
     { name: 'Natalizumab' },
     { name: 'Natazia' },
     { name: 'Nateglinide' },
     { name: 'Natesto' },
     { name: 'Natroba' },
     { name: 'NatureThroid' },
     { name: 'Navane' },
     { name: 'Nebivolol' },
     { name: 'Necon 1  35' },
     { name: 'Necon 1  50' },
     { name: 'Necon 7  7  7' },
     { name: 'Nefazodone' },
     { name: 'Nembutal Sodium' },
     { name: 'NeoPolyDex' },
     { name: 'NeoSynephrine Nasal' },
     { name: 'Neosporin' },
     { name: 'Neulasta' },
     { name: 'Neupogen' },
     { name: 'Neupro' },
     { name: 'Neurontin' },
     { name: 'NeutraSal' },
     { name: 'Nexafed Nasal Decongestant' },
     { name: 'Nexavar' },
     { name: 'Nexium' },
     { name: 'Nexplanon' },
     { name: 'Next Choice' },
     { name: 'Niacin' },
     { name: 'Niacin  simvastatin' },
     { name: 'Niaspan' },
     { name: 'Nicoderm CQ' },
     { name: 'Nicorette' },
     { name: 'Nicotine' },
     { name: 'Nicotrol Inhaler' },
     { name: 'Nicotrol NS' },
     { name: 'Nifedipine' },
     { name: 'Nikki' },
     { name: 'Nilotinib' },
     { name: 'Nimodipine' },
     { name: 'Nimotop' },
     { name: 'Niravam' },
     { name: 'Nitrofurantoin' },
     { name: 'Nitroglycerin' },
     { name: 'Nitrolingual Pumpspray' },
     { name: 'Nivolumab' },
     { name: 'Nizatidine' },
     { name: 'Nizoral' },
     { name: 'NoDoz' },
     { name: 'Nonoxynol 9' },
     { name: 'NoraBe' },
     { name: 'Norco' },
     { name: 'Norel SR' },
     { name: 'Norepinephrine' },
     { name: 'Norethindrone' },
     { name: 'Norflex' },
     { name: 'Norgesic' },
     { name: 'Noritate' },
     { name: 'Noroxin' },
     { name: 'Norpace' },
     { name: 'Norpace CR' },
     { name: 'Norpramin' },
     { name: 'Nortrel 1  35' },
     { name: 'Nortrel 7  7  7' },
     { name: 'Nortriptyline' },
     { name: 'Norvasc' },
     { name: 'Nostrilla' },
     { name: 'Novantrone' },
     { name: 'NovoLog FlexPen' },
     { name: 'NovoLog Mix 70  30' },
     { name: 'Novolin 70  30' },
     { name: 'Novolog' },
     { name: 'Nplate' },
     { name: 'NuOx' },
     { name: 'Nubain' },
     { name: 'Nucynta' },
     { name: 'Nucynta ER' },
     { name: 'Nuedexta' },
     { name: 'Nutropin' },
     { name: 'NuvaRing' },
     { name: 'Nuvessa' },
     { name: 'Nuvigil' },
     { name: 'Nyamyc' },
     { name: 'Nystatin' },
     { name: 'Nystatin  triamcinolone' },
     { name: 'Nystop' },
     { name: 'Ocella' },
     { name: 'Octreotide' },
     { name: 'Ocular lubricant' },
     { name: 'Odefsey' },
     { name: 'Ogestrel28' },
     { name: 'Olanzapine' },
     { name: 'Oleptro' },
     { name: 'Olmesartan' },
     { name: 'Olodaterol' },
     { name: 'Olodaterol  tiotropium' },
     { name: 'Olopatadine' },
     { name: 'Olux' },
     { name: 'Olysio' },
     { name: 'Omalizumab' },
     { name: 'Omega3 polyunsaturated fatty acids' },
     { name: 'Omeprazole' },
     { name: 'Omeprazole  sodium bicarbonate' },
     { name: 'Omnaris' },
     { name: 'Omnicef' },
     { name: 'OnabotulinumtoxinA' },
     { name: 'Ondansetron' },
     { name: 'Onexton' },
     { name: 'Onfi' },
     { name: 'Onglyza' },
     { name: 'Opana' },
     { name: 'Opana ER' },
     { name: 'Opcicon OneStep' },
     { name: 'OpconA' },
     { name: 'Opdivo' },
     { name: 'Opium' },
     { name: 'Opium Deodorized' },
     { name: 'Opsumit' },
     { name: 'Oracea' },
     { name: 'Orajel' },
     { name: 'Oramorph SR' },
     { name: 'Orap' },
     { name: 'Orapred' },
     { name: 'Oraqix' },
     { name: 'Orencia' },
     { name: 'Orlistat' },
     { name: 'Ornex' },
     { name: 'Orphenadrine' },
     { name: 'Orsythia' },
     { name: 'Ortho Cyclen' },
     { name: 'Ortho D' },
     { name: 'Ortho Evra' },
     { name: 'Ortho Micronor' },
     { name: 'Ortho TriCyclen' },
     { name: 'Ortho TriCyclen Lo' },
     { name: 'OrthoCept' },
     { name: 'OrthoNovum 1  35' },
     { name: 'OrthoNovum 7  7  7' },
     { name: 'Orthovisc' },
     { name: 'Orudis' },
     { name: 'Orudis KT' },
     { name: 'Oseltamivir' },
     { name: 'OsmoPrep' },
     { name: 'Ospemifene' },
     { name: 'Osphena' },
     { name: 'Otezla' },
     { name: 'Ovcon 35' },
     { name: 'Ovide' },
     { name: 'Oxaprozin' },
     { name: 'Oxaydo' },
     { name: 'Oxazepam' },
     { name: 'Oxcarbazepine' },
     { name: 'Oxistat' },
     { name: 'Oxtellar XR' },
     { name: 'OxyContin' },
     { name: 'Oxybutynin' },
     { name: 'Oxycodone' },
     { name: 'Oxydose' },
     { name: 'Oxymetazoline' },
     { name: 'Oxymorphone' },
     { name: 'Oxytrol' },
     { name: 'Ozurdex' },
     { name: 'PEG3350 with Electolytes' },
     { name: 'Pacerone' },
     { name: 'Paclitaxel' },
     { name: 'Palbociclib' },
     { name: 'Paliperidone' },
     { name: 'Pamabrom' },
     { name: 'Pamelor' },
     { name: 'Pamine Forte' },
     { name: 'Pancrelipase' },
     { name: 'Panlor DC' },
     { name: 'Panlor SS' },
     { name: 'Pantoprazole' },
     { name: 'ParaGard' },
     { name: 'Parafon Forte DSC' },
     { name: 'Parathyroid hormone' },
     { name: 'Paregoric' },
     { name: 'Parlodel' },
     { name: 'Parnate' },
     { name: 'Paroxetine' },
     { name: 'Pataday' },
     { name: 'Patanase' },
     { name: 'Patanol' },
     { name: 'Paxil' },
     { name: 'Paxil CR' },
     { name: 'Pazeo' },
     { name: 'Pazopanib' },
     { name: 'Pegaptanib' },
     { name: 'Pegasys' },
     { name: 'Pegfilgrastim' },
     { name: 'Peginterferon alfa2a' },
     { name: 'Pegloticase' },
     { name: 'Pembrolizumab' },
     { name: 'Pemetrexed' },
     { name: 'Pemoline' },
     { name: 'Penciclovir' },
     { name: 'Penicillin VK' },
     { name: 'Penicillin g benzathine' },
     { name: 'Penicillin v potassium' },
     { name: 'Pennsaid' },
     { name: 'Pentasa' },
     { name: 'Pentazocine' },
     { name: 'Pentosan polysulfate sodium' },
     { name: 'Pentoxifylline' },
     { name: 'PeptoBismol' },
     { name: 'Perampanel' },
     { name: 'Percocet' },
     { name: 'Percodan' },
     { name: 'Peridex' },
     { name: 'Perindopril' },
     { name: 'Periogard' },
     { name: 'Permethrin' },
     { name: 'Perphenazine' },
     { name: 'Pexeva' },
     { name: 'Phenazopyridine' },
     { name: 'Phendiet' },
     { name: 'Phendimetrazine' },
     { name: 'Phenelzine' },
     { name: 'Phenergan' },
     { name: 'Phenobarbital' },
     { name: 'Phenol' },
     { name: 'Phentermine' },
     { name: 'Phentermine  topiramate' },
     { name: 'Phenylephrine' },
     { name: 'Phenylephrine  pramoxine' },
     { name: 'Phenytoin' },
     { name: 'Phillips Milk of Magnesia' },
     { name: 'Phosphorated carbohydrate solution' },
     { name: 'Pilocarpine' },
     { name: 'Pimecrolimus' },
     { name: 'Pimozide' },
     { name: 'Pimtrea' },
     { name: 'PinX' },
     { name: 'Pioglitazone' },
     { name: 'Piperacillin  tazobactam' },
     { name: 'Pirbuterol' },
     { name: 'Piroxicam' },
     { name: 'Pitavastatin' },
     { name: 'Pitocin' },
     { name: 'Plan B' },
     { name: 'Plan B OneStep' },
     { name: 'Plaquenil' },
     { name: 'Plavix' },
     { name: 'Plecanatide' },
     { name: 'Plegridy' },
     { name: 'Pletal' },
     { name: 'Pneumococcal 13valent vaccine' },
     { name: 'Pneumococcal 23polyvalent vaccine' },
     { name: 'Podofilox' },
     { name: 'Poly Iron' },
     { name: 'Polycarbophil' },
     { name: 'Polyethylene glycol 3350' },
     { name: 'Polyethylene glycol 3350 with electrolytes' },
     { name: 'Polymyxin b  trimethoprim' },
     { name: 'Ponatinib' },
     { name: 'Ponstel' },
     { name: 'Portia' },
     { name: 'Potassium chloride' },
     { name: 'Potassium citrate' },
     { name: 'Pradaxa' },
     { name: 'Praluent' },
     { name: 'Pramipexole' },
     { name: 'Pramlintide' },
     { name: 'Pramosone' },
     { name: 'Pramoxine' },
     { name: 'Pramoxine  zinc oxide' },
     { name: 'Prandin' },
     { name: 'Prascion RA' },
     { name: 'Prasugrel' },
     { name: 'Pravastatin' },
     { name: 'Prazosin' },
     { name: 'Prednisolone' },
     { name: 'Prednisone' },
     { name: 'Pregabalin' },
     { name: 'Premarin' },
     { name: 'Premarin Vaginal' },
     { name: 'Premphase' },
     { name: 'Prempro' },
     { name: 'Premsyn PMS' },
     { name: 'Prenatabs FA' },
     { name: 'Prenatal Plus' },
     { name: 'Prepopik' },
     { name: 'Prevacid' },
     { name: 'Prevalite' },
     { name: 'Prevident 5000 Plus' },
     { name: 'Previfem' },
     { name: 'Prevnar 13' },
     { name: 'Prevpac' },
     { name: 'Prezcobix' },
     { name: 'Prezista' },
     { name: 'Prialt' },
     { name: 'Prilosec' },
     { name: 'Prilosec OTC' },
     { name: 'Primatene' },
     { name: 'Primatene Mist' },
     { name: 'Primidone' },
     { name: 'Prinivil' },
     { name: 'Pristiq' },
     { name: 'Privine' },
     { name: 'ProAir HFA' },
     { name: 'ProAir RespiClick' },
     { name: 'Probenecid' },
     { name: 'Prochlorperazine' },
     { name: 'Procrit' },
     { name: 'Proctofoam' },
     { name: 'ProctosolHC' },
     { name: 'Procyclidine' },
     { name: 'Prodrin' },
     { name: 'Progesterone' },
     { name: 'Prograf' },
     { name: 'Prolensa' },
     { name: 'Prolia' },
     { name: 'Prolixin' },
     { name: 'Promacta' },
     { name: 'Promethazine' },
     { name: 'Promethazine DM' },
     { name: 'Prometrium' },
     { name: 'Propafenone' },
     { name: 'Propecia' },
     { name: 'Propofol' },
     { name: 'Propoxyphene' },
     { name: 'Propranolol' },
     { name: 'Propulsid' },
     { name: 'Prosom' },
     { name: 'Prostigmin Bromide' },
     { name: 'Protonix' },
     { name: 'Protonix IV' },
     { name: 'Protopic' },
     { name: 'Provenge' },
     { name: 'Proventil' },
     { name: 'Proventil HFA' },
     { name: 'Provera' },
     { name: 'Provigil' },
     { name: 'Prozac' },
     { name: 'Prozac Weekly' },
     { name: 'Pseudoephedrine' },
     { name: 'Pseudoephedrine  triprolidine' },
     { name: 'Psoriasin' },
     { name: 'Psyllium' },
     { name: 'Pulmicort Respules' },
     { name: 'Pulmicort Turbuhaler' },
     { name: 'Pulmozyme' },
     { name: 'Pylera' },
     { name: 'Pyrantel' },
     { name: 'Pyridium' },
     { name: 'Pyridostigmine' },
     { name: 'Pyrithione zinc' },
     { name: 'QDryl' },
     { name: 'QNASL' },
     { name: 'QTapp DM' },
     { name: 'Qsymia' },
     { name: 'Quasense' },
     { name: 'Questran Light' },
     { name: 'Quetiapine' },
     { name: 'Quillivant XR' },
     { name: 'Quinapril' },
     { name: 'Quinine' },
     { name: 'Qvar' },
     { name: 'RTanna' },
     { name: 'Rabeprazole' },
     { name: 'Racepinephrine' },
     { name: 'RadiaPlexRx' },
     { name: 'Radium 223 dichloride' },
     { name: 'Rajani' },
     { name: 'Raltegravir' },
     { name: 'Ramelteon' },
     { name: 'Ramipril' },
     { name: 'Ranexa' },
     { name: 'Ranibizumab' },
     { name: 'Ranitidine' },
     { name: 'Ranolazine' },
     { name: 'Rapaflo' },
     { name: 'Rebif' },
     { name: 'Rebif Rebidose' },
     { name: 'Reclast' },
     { name: 'Reclipsen' },
     { name: 'Rectiv' },
     { name: 'Red yeast rice' },
     { name: 'Regadenoson' },
     { name: 'Reglan' },
     { name: 'Regorafenib' },
     { name: 'Relafen' },
     { name: 'Relenza' },
     { name: 'Relistor' },
     { name: 'Relpax' },
     { name: 'Remeron' },
     { name: 'Remeron SolTab' },
     { name: 'Remicade' },
     { name: 'Renvela' },
     { name: 'Repaglinide' },
     { name: 'Repatha' },
     { name: 'Reprexain' },
     { name: 'Requip' },
     { name: 'Requip XL' },
     { name: 'Restasis' },
     { name: 'Restoril' },
     { name: 'Retapamulin' },
     { name: 'RetinA' },
     { name: 'Revatio' },
     { name: 'Revia' },
     { name: 'Revlimid' },
     { name: 'Rexulti' },
     { name: 'Rezira' },
     { name: 'Rhinocort Aqua' },
     { name: 'Rho d immune globulin' },
     { name: 'Rhofade' },
     { name: 'Ribasphere' },
     { name: 'Ribavirin' },
     { name: 'Riboflavin' },
     { name: 'Rifabutin' },
     { name: 'Rifampin' },
     { name: 'Rifaximin' },
     { name: 'Risedronate' },
     { name: 'Risperdal' },
     { name: 'Risperdal Consta' },
     { name: 'Risperdal MTab' },
     { name: 'Risperidone' },
     { name: 'Ritalin' },
     { name: 'Ritalin LA' },
     { name: 'RitalinSR' },
     { name: 'Ritonavir' },
     { name: 'Rituxan' },
     { name: 'Rituximab' },
     { name: 'Rivaroxaban' },
     { name: 'Rivastigmine' },
     { name: 'Rizatriptan' },
     { name: 'Robaxin' },
     { name: 'Robaxin750' },
     { name: 'Robitussin Cough  Chest Congestion DM' },
     { name: 'Rocaltrol' },
     { name: 'Rocephin' },
     { name: 'Rocuronium' },
     { name: 'Roflumilast' },
     { name: 'Rogaine' },
     { name: 'Rogaine Mens Extra Strength' },
     { name: 'Rogaine Womens' },
     { name: 'Romiplostim' },
     { name: 'Ropinirole' },
     { name: 'Rosac' },
     { name: 'Rosiglitazone' },
     { name: 'Rosula' },
     { name: 'Rosuvastatin' },
     { name: 'Rotigotine' },
     { name: 'Rowasa' },
     { name: 'Roxicet' },
     { name: 'Roxicodone' },
     { name: 'Rozerem' },
     { name: 'Rozex' },
     { name: 'Ruxolitinib' },
     { name: 'Rydapt' },
     { name: 'Rynatan' },
     { name: 'Rytary' },
     { name: 'Rythmol' },
     { name: 'Rythmol SR' },
     { name: 'Ryzolt' },
     { name: 'SMZTMP DS' },
     { name: 'Saccharomyces boulardii lyo' },
     { name: 'Sacubitril  valsartan' },
     { name: 'Sadenosylmethionine' },
     { name: 'Safyral' },
     { name: 'Salagen' },
     { name: 'Salicylic acid' },
     { name: 'Salicylic acid  sulfur' },
     { name: 'Saliva substitutes' },
     { name: 'SalivaMAX' },
     { name: 'Salmeterol' },
     { name: 'Salofalk' },
     { name: 'Salonpas Pain Patch' },
     { name: 'Sanctura' },
     { name: 'Sanctura XR' },
     { name: 'Sancuso' },
     { name: 'Sandostatin' },
     { name: 'Sandostatin LAR Depot' },
     { name: 'Sansert' },
     { name: 'Saphris' },
     { name: 'Sarafem' },
     { name: 'Sarna Sensitive' },
     { name: 'Savella' },
     { name: 'Saw palmetto' },
     { name: 'Saxagliptin' },
     { name: 'Saxenda' },
     { name: 'Scopolamine' },
     { name: 'Seasonale' },
     { name: 'Seasonique' },
     { name: 'Sebulex' },
     { name: 'Secobarbital' },
     { name: 'Seconal' },
     { name: 'Seconal Sodium' },
     { name: 'Secukinumab' },
     { name: 'Selegiline' },
     { name: 'Selenium sulfide' },
     { name: 'Selexipag' },
     { name: 'Selsun Blue' },
     { name: 'Senna' },
     { name: 'Senna Plus' },
     { name: 'Senokot' },
     { name: 'Senokot S' },
     { name: 'Sensipar' },
     { name: 'Septra' },
     { name: 'Serax' },
     { name: 'Seroquel' },
     { name: 'Seroquel XR' },
     { name: 'Serostim' },
     { name: 'Sertraline' },
     { name: 'Serzone' },
     { name: 'Sevelamer' },
     { name: 'Sharobel' },
     { name: 'SildecPE DM' },
     { name: 'Sildenafil' },
     { name: 'Silenor' },
     { name: 'Siliq' },
     { name: 'Silodosin' },
     { name: 'Silvadene' },
     { name: 'Silver' },
     { name: 'Silver nitrate' },
     { name: 'Silver sulfadiazine' },
     { name: 'Simbrinza' },
     { name: 'Simcor' },
     { name: 'Simethicone' },
     { name: 'Simply Sleep' },
     { name: 'Simponi' },
     { name: 'Simponi Aria' },
     { name: 'Simvastatin' },
     { name: 'SineOff Maximum Strength' },
     { name: 'Sinemet' },
     { name: 'Sinequan' },
     { name: 'Singulair' },
     { name: 'SipuleucelT' },
     { name: 'Sitagliptin' },
     { name: 'Sitavig' },
     { name: 'Skelaxin' },
     { name: 'Sklice' },
     { name: 'Skyla' },
     { name: 'Sleep Aid' },
     { name: 'SloNiacin' },
     { name: 'Slow Fe' },
     { name: 'Sodium biphosphate  sodium phosphate' },
     { name: 'Sodium ferric gluconate complex' },
     { name: 'Sodium hyaluronate' },
     { name: 'Sodium oxybate' },
     { name: 'Sofosbuvir' },
     { name: 'Sofosbuvir  velpatasvir' },
     { name: 'Solaraze' },
     { name: 'Solarcaine Burn Relief' },
     { name: 'Solifenacin' },
     { name: 'Solodyn' },
     { name: 'SoluMedrol' },
     { name: 'Soma' },
     { name: 'Soma Compound' },
     { name: 'Soma Compound with Codeine' },
     { name: 'Somatropin' },
     { name: 'Sominex' },
     { name: 'Somnote' },
     { name: 'Sonata' },
     { name: 'Soolantra' },
     { name: 'Sorafenib' },
     { name: 'Sorbitol' },
     { name: 'Sotalol' },
     { name: 'Sotalol Hydrochloride AF' },
     { name: 'Sotret' },
     { name: 'Sovaldi' },
     { name: 'Spectracef' },
     { name: 'Spinosad' },
     { name: 'Spiriva' },
     { name: 'Spiriva Respimat' },
     { name: 'Spironolactone' },
     { name: 'Sporanox' },
     { name: 'Sprintec' },
     { name: 'Sprix' },
     { name: 'Sprycel' },
     { name: 'Sronyx' },
     { name: 'St johns wort' },
     { name: 'Stadol' },
     { name: 'Stalevo' },
     { name: 'Staxyn' },
     { name: 'Stelara' },
     { name: 'Stelazine' },
     { name: 'Stendra' },
     { name: 'Sterapred' },
     { name: 'Sterapred DS' },
     { name: 'Stimate' },
     { name: 'Stiolto Respimat' },
     { name: 'Strattera' },
     { name: 'Stribild' },
     { name: 'Striverdi Respimat' },
     { name: 'Stromectol' },
     { name: 'Sublimaze' },
     { name: 'Suboxone' },
     { name: 'Subsys' },
     { name: 'Subutex' },
     { name: 'Succinylcholine' },
     { name: 'Sucralfate' },
     { name: 'Sucroferric oxyhydroxide' },
     { name: 'Sudafed PE Congestion' },
     { name: 'Sulfacetamide sodium' },
     { name: 'Sulfacetamide sodium  sulfur' },
     { name: 'Sulfamethoxazole  trimethoprim' },
     { name: 'Sulfasalazine' },
     { name: 'Sulfazine' },
     { name: 'Sulindac' },
     { name: 'Sumatriptan' },
     { name: 'Sumavel DosePro' },
     { name: 'Sunitinib' },
     { name: 'Supartz' },
     { name: 'Supprelin LA' },
     { name: 'Suprax' },
     { name: 'Suprenza' },
     { name: 'Suprep Bowel Prep Kit' },
     { name: 'Sustiva' },
     { name: 'Sutent' },
     { name: 'Suvorexant' },
     { name: 'Symax Duotab' },
     { name: 'Symbicort' },
     { name: 'Symbyax' },
     { name: 'Symlin' },
     { name: 'Synalar Ointment' },
     { name: 'Synarel' },
     { name: 'Synjardy' },
     { name: 'Synthroid' },
     { name: 'Synvisc' },
     { name: 'SynviscOne' },
     { name: 'Systane' },
     { name: 'Systane Ultra' },
     { name: 'Taclonex' },
     { name: 'Taclonex Scalp' },
     { name: 'Tacrolimus' },
     { name: 'Tadalafil' },
     { name: 'Take Action' },
     { name: 'Taltz' },
     { name: 'Talwin Nx' },
     { name: 'Tambocor' },
     { name: 'Tamiflu' },
     { name: 'Tamoxifen' },
     { name: 'Tamsulosin' },
     { name: 'Tanzeum' },
     { name: 'Tapentadol' },
     { name: 'Tarceva' },
     { name: 'Targretin' },
     { name: 'Tarina Fe 1  20' },
     { name: 'Tarka' },
     { name: 'Tasigna' },
     { name: 'Tasimelteon' },
     { name: 'Tavaborole' },
     { name: 'Taxol' },
     { name: 'Taxotere' },
     { name: 'Taytulla' },
     { name: 'Tazarotene' },
     { name: 'Tazorac' },
     { name: 'Tears Again' },
     { name: 'Tecfidera' },
     { name: 'Tegaserod' },
     { name: 'Tegretol' },
     { name: 'Tegretol XR' },
     { name: 'Tekturna' },
     { name: 'Tekturna HCT' },
     { name: 'Telaprevir' },
     { name: 'Telmisartan' },
     { name: 'Temazepam' },
     { name: 'Temodar' },
     { name: 'Temovate' },
     { name: 'Tenex' },
     { name: 'Tenofovir' },
     { name: 'Tenormin' },
     { name: 'Tenuate' },
     { name: 'Tenuate Dospan' },
     { name: 'Terazol 3' },
     { name: 'Terazosin' },
     { name: 'Terbinafine' },
     { name: 'Terbutaline' },
     { name: 'Terconazole' },
     { name: 'Teriflunomide' },
     { name: 'Teriparatide' },
     { name: 'Tesamorelin' },
     { name: 'Tessalon' },
     { name: 'Tessalon Perles' },
     { name: 'Testim' },
     { name: 'Testopel' },
     { name: 'Testosterone' },
     { name: 'Tetracycline' },
     { name: 'Tetrahydrozoline  zinc sulfate' },
     { name: 'TevTropin' },
     { name: 'Theophylline' },
     { name: 'TheraTears' },
     { name: 'Thioridazine' },
     { name: 'Thiothixene' },
     { name: 'Thorazine' },
     { name: 'Thyroid desiccated' },
     { name: 'Tiagabine' },
     { name: 'Ticagrelor' },
     { name: 'Tigan' },
     { name: 'Tikosyn' },
     { name: 'Tilmanocept' },
     { name: 'Timolol' },
     { name: 'Tindamax' },
     { name: 'Tinidazole' },
     { name: 'Tinzaparin' },
     { name: 'Tioconazole' },
     { name: 'Tiotropium' },
     { name: 'Tirosint' },
     { name: 'Tivicay' },
     { name: 'Tizanidine' },
     { name: 'TobraDex' },
     { name: 'Tobramycin' },
     { name: 'Tocilizumab' },
     { name: 'Tofacitinib' },
     { name: 'Tofranil' },
     { name: 'Tolak' },
     { name: 'Tolectin DS' },
     { name: 'Tolnaftate' },
     { name: 'Tolterodine' },
     { name: 'Topamax' },
     { name: 'Topicort' },
     { name: 'Topiramate' },
     { name: 'ToprolXL' },
     { name: 'Toradol' },
     { name: 'Toradol IV  IM' },
     { name: 'Torsemide' },
     { name: 'Toujeo' },
     { name: 'Toujeo Solostar' },
     { name: 'Toviaz' },
     { name: 'Tradjenta' },
     { name: 'Tramadol' },
     { name: 'Tranexamic acid' },
     { name: 'TransdermScop' },
     { name: 'Tranxene' },
     { name: 'Tranxene SD' },
     { name: 'Tranylcypromine' },
     { name: 'Travatan' },
     { name: 'Travatan Z' },
     { name: 'Travoprost' },
     { name: 'Trazodone' },
     { name: 'Trelstar' },
     { name: 'Trental' },
     { name: 'Treprostinil' },
     { name: 'Tresiba' },
     { name: 'TretinX' },
     { name: 'Tretinoin' },
     { name: 'Treximet' },
     { name: 'Trezix' },
     { name: 'TriCor' },
     { name: 'TriEstarylla' },
     { name: 'TriLinyah' },
     { name: 'TriLoEstarylla' },
     { name: 'TriLoMarzia' },
     { name: 'TriLoSprintec' },
     { name: 'TriLuma' },
     { name: 'TriLyte' },
     { name: 'TriNessa' },
     { name: 'TriNessa Lo' },
     { name: 'TriPrevifem' },
     { name: 'TriSprintec' },
     { name: 'Triamcinolone' },
     { name: 'Triamterene' },
     { name: 'Triazolam' },
     { name: 'Tribenzor' },
     { name: 'Trifluoperazine' },
     { name: 'Trihexyphenidyl' },
     { name: 'Trilafon' },
     { name: 'Trileptal' },
     { name: 'Trilipix' },
     { name: 'Trilisate' },
     { name: 'Trimethobenzamide' },
     { name: 'Trimethoprim' },
     { name: 'Trimipramine' },
     { name: 'Trintellix' },
     { name: 'Triple Antibiotic' },
     { name: 'Triptorelin' },
     { name: 'Triumeq' },
     { name: 'Trivora' },
     { name: 'Trolamine salicylate' },
     { name: 'Tropicamide' },
     { name: 'Trospium' },
     { name: 'Trulance' },
     { name: 'Trulicity' },
     { name: 'Trusopt' },
     { name: 'Truvada' },
     { name: 'Tryptophan' },
     { name: 'Tudorza Pressair' },
     { name: 'Tums Regular Strength' },
     { name: 'TussiCaps' },
     { name: 'Tussionex Pennkinetic' },
     { name: 'Tykerb' },
     { name: 'Tylenol' },
     { name: 'Tylenol 8 Hour' },
     { name: 'Tylenol Allergy MultiSymptom Nighttime' },
     { name: 'Tylenol Cold' },
     { name: 'Tylenol PM' },
     { name: 'Tylenol with Codeine 3' },
     { name: 'Tylenol with Codeine 4' },
     { name: 'Tylox' },
     { name: 'Tysabri' },
     { name: 'Tyvaso' },
     { name: 'Ubiquinone' },
     { name: 'Uceris' },
     { name: 'Ulipristal' },
     { name: 'Uloric' },
     { name: 'Ultracet' },
     { name: 'Ultram' },
     { name: 'Ultram ER' },
     { name: 'Ultram ODT' },
     { name: 'Umeclidinium' },
     { name: 'Umeclidinium  vilanterol' },
     { name: 'Unasyn' },
     { name: 'Undecylenic acid' },
     { name: 'Unisom SleepGels' },
     { name: 'Unisom SleepTabs' },
     { name: 'Univasc' },
     { name: 'Uptravi' },
     { name: 'Urea' },
     { name: 'Uribel' },
     { name: 'Uricalm' },
     { name: 'Urispas' },
     { name: 'Uristat' },
     { name: 'Uroxatral' },
     { name: 'Urso' },
     { name: 'Ursodiol' },
     { name: 'Ustekinumab' },
     { name: 'VESIcare' },
     { name: 'Vagifem' },
     { name: 'Vagistat1' },
     { name: 'Valacyclovir' },
     { name: 'Valerian' },
     { name: 'Valium' },
     { name: 'Valproic acid' },
     { name: 'Valsartan' },
     { name: 'Valtrex' },
     { name: 'Valturna' },
     { name: 'Vancomycin' },
     { name: 'Vandazole' },
     { name: 'Vaniqa' },
     { name: 'VanoxideHC' },
     { name: 'Vanspar' },
     { name: 'Vantin' },
     { name: 'Vardenafil' },
     { name: 'Varenicline' },
     { name: 'Vascepa' },
     { name: 'Vasotec' },
     { name: 'Vectibix' },
     { name: 'Vectical' },
     { name: 'Vedolizumab' },
     { name: 'Velivet' },
     { name: 'Veltin' },
     { name: 'Venlafaxine' },
     { name: 'Venofer' },
     { name: 'Ventolin' },
     { name: 'Ventolin HFA' },
     { name: 'Veramyst' },
     { name: 'Verapamil' },
     { name: 'Versed' },
     { name: 'Vestura' },
     { name: 'Viagra' },
     { name: 'Viberzi' },
     { name: 'Vibramycin' },
     { name: 'Vicks Sinex 12Hour Decongestant Nasal Spray' },
     { name: 'Vicks Sinex Nasal Spray old formulation' },
     { name: 'Vicodin' },
     { name: 'Vicodin ES' },
     { name: 'Vicodin HP' },
     { name: 'Vicoprofen' },
     { name: 'Victoza' },
     { name: 'Vidaza' },
     { name: 'Vienva' },
     { name: 'Vigamox' },
     { name: 'Viibryd' },
     { name: 'Vilazodone' },
     { name: 'Vimovo' },
     { name: 'Vimpat' },
     { name: 'Viorele' },
     { name: 'Viread' },
     { name: 'VisRx Dose Pack' },
     { name: 'Visine Totality MultiSymptom Relief' },
     { name: 'VisineA' },
     { name: 'Vistaril' },
     { name: 'Vitafol Ultra' },
     { name: 'Vitamin B12' },
     { name: 'Vitamin B2' },
     { name: 'Vitamin D2' },
     { name: 'Vitamin D3' },
     { name: 'Vivarin' },
     { name: 'VivelleDot' },
     { name: 'Vivitrol' },
     { name: 'Voltaren' },
     { name: 'Voltaren Gel' },
     { name: 'VoltarenXR' },
     { name: 'Volumen' },
     { name: 'Vortioxetine' },
     { name: 'Vosol HC' },
     { name: 'Vospire ER' },
     { name: 'Votrient' },
     { name: 'Vraylar' },
     { name: 'Vytorin' },
     { name: 'Vyvanse' },
     { name: 'WP Thyroid' },
     { name: 'Warfarin' },
     { name: 'Wart Remover' },
     { name: 'Welchol' },
     { name: 'Wellbutrin' },
     { name: 'Wellbutrin SR' },
     { name: 'Wellbutrin XL' },
     { name: 'Westhroid' },
     { name: 'XViate' },
     { name: 'Xalatan' },
     { name: 'Xalkori' },
     { name: 'Xanax' },
     { name: 'Xanax XR' },
     { name: 'Xarelto' },
     { name: 'Xeljanz' },
     { name: 'Xeljanz XR' },
     { name: 'Xeloda' },
     { name: 'Xenaderm' },
     { name: 'Xenical' },
     { name: 'Xeomin' },
     { name: 'Xerac AC' },
     { name: 'Xgeva' },
     { name: 'Xifaxan' },
     { name: 'Xiidra' },
     { name: 'Xolair' },
     { name: 'Xolegel' },
     { name: 'Xopenex' },
     { name: 'Xopenex HFA' },
     { name: 'Xtampza ER' },
     { name: 'Xulane' },
     { name: 'Xylocaine Jelly' },
     { name: 'Xylometazoline' },
     { name: 'Xyrem' },
     { name: 'Xyzal' },
     { name: 'Yasmin' },
     { name: 'Yaz' },
     { name: 'Yellow fever vaccine' },
     { name: 'Yohimbine' },
     { name: 'Yuvafem' },
     { name: 'Zaditor' },
     { name: 'Zafirlukast' },
     { name: 'Zaleplon' },
     { name: 'Zanaflex' },
     { name: 'Zanamivir' },
     { name: 'Zantac' },
     { name: 'Zantac 150' },
     { name: 'Zantryl' },
     { name: 'Zarah' },
     { name: 'Zarontin' },
     { name: 'Zaroxolyn' },
     { name: 'ZeasorbAF' },
     { name: 'Zebeta' },
     { name: 'Zecuity' },
     { name: 'Zegerid' },
     { name: 'Zegerid OTC' },
     { name: 'Zelapar' },
     { name: 'Zelboraf' },
     { name: 'Zelnorm' },
     { name: 'Zemaira' },
     { name: 'Zenatane' },
     { name: 'Zenpep' },
     { name: 'Zepatier' },
     { name: 'Zestoretic' },
     { name: 'Zestril' },
     { name: 'Zetia' },
     { name: 'Ziac' },
     { name: 'Ziana' },
     { name: 'Zinc oxide' },
     { name: 'Zioptan' },
     { name: 'Ziprasidone' },
     { name: 'Zipsor' },
     { name: 'Zirgan' },
     { name: 'Zithromax' },
     { name: 'Zocor' },
     { name: 'Zofran' },
     { name: 'Zofran ODT' },
     { name: 'Zohydro ER' },
     { name: 'Zoladex' },
     { name: 'Zoledronic acid' },
     { name: 'Zolmitriptan' },
     { name: 'Zoloft' },
     { name: 'Zolpidem' },
     { name: 'Zolpimist' },
     { name: 'Zometa' },
     { name: 'Zomig' },
     { name: 'ZomigZMT' },
     { name: 'Zonegran' },
     { name: 'Zonisamide' },
     { name: 'Zorvolex' },
     { name: 'Zoster vaccine live' },
     { name: 'Zostrix' },
     { name: 'Zovia' },
     { name: 'Zovia 1  35' },
     { name: 'Zovia 1  50' },
     { name: 'Zovirax' },
     { name: 'Zovirax Cream' },
     { name: 'Zubsolv' },
     { name: 'Zutripro' },
     { name: 'Zyban' },
     { name: 'Zyclara' },
     { name: 'Zymar' },
     { name: 'Zyprexa' },
     { name: 'Zyprexa Zydis' },
     { name: 'Zyrtec' },
     { name: 'ZyrtecD' },
     { name: 'Zytiga' },
     { name: 'Zyvox' },
];
